// GENERATED by tools/fixtures/generate_showcase.ts; topology extracted offline.
import { unpackSample } from "./showcaseFormat";
import { SAMPLE as sample0 } from "./showcaseTree";
import { SAMPLE as sample1 } from "./showcaseVolume";
import { SAMPLE as sample2 } from "./showcaseMaxa";
export const SHOWCASE_SAMPLES = [unpackSample(sample0), unpackSample(sample1), unpackSample(sample2)];
