import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id), scene=new T.Scene();scene.background=new T.Color('#dce3e8');
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;$('viewport').append(renderer.domElement);
const camera=new T.PerspectiveCamera(38,1,.01,5000);camera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;
scene.add(new T.HemisphereLight(0xffffff,0x64758a,2.4));let sun=new T.DirectionalLight(0xffffff,3);sun.position.set(80,-120,180);scene.add(sun);
let directContact=false;
let root=new T.Group(),cutGroup=new T.Group();scene.add(root,cutGroup);let entries=[],bounds=new T.Box3(),normal=new T.Vector3(1,0,0),clip=new T.Plane(normal,-34),flip=1,selected=null,buildToken=0,timer;
let guide=new T.PlaneHelper(clip,100,0xeb772d);guide.visible=false;scene.add(guide);
const colors={shell_base:0x647582,shell_lid:0x8a9ba6,button:0xefbe36,pcb:0x208765,logo_white:0xf4f2e8,lightpipe:0x80d4c9,nickel:0xb3c0c8,fastener:0x9aafb8,seal:0x5a6560,switch_body:0xc361ce,terminal:0x1d8d49,gold:0xd9b753,white_nylon:0xeee8d4};
function draw(){renderer.render(scene,camera)}controls.addEventListener('change',draw);
function resize(){let v=$('viewport');renderer.setSize(v.clientWidth,v.clientHeight);camera.aspect=v.clientWidth/v.clientHeight;camera.updateProjectionMatrix();draw()}window.addEventListener('resize',resize);
function axis(){return 'XYZ'.indexOf($('axis').value)}
function sync(){const a=axis(),p=+$('position').value;normal.set(0,0,0).setComponent(a,flip);clip.set(normal,-p*flip);let planes=$('section').checked?[clip]:[];
 for(let e of entries){for(let m of [e.mesh.material,e.edge.material,e.hidden.material])m.clippingPlanes=planes;e.edge.visible=$('edges').checked;e.hidden.visible=$('hidden').checked;e.mesh.material.opacity=$('ghost').checked&&e.shell ? .24 : 1;e.mesh.material.transparent=e.mesh.material.opacity<1;e.mesh.material.depthWrite=!e.mesh.material.transparent;}
 guide.visible=$('section').checked&&$('plane').checked;guide.updateMatrixWorld();clearTimeout(timer);timer=setTimeout(sectionFaces,70);draw();}
function fit(){let b=new T.Box3();for(let e of entries)if(e.group.visible)b.expandByObject(e.mesh);if(b.isEmpty())return;let c=b.getCenter(new T.Vector3()),s=b.getSize(new T.Vector3()).length();controls.target.copy(c);camera.position.copy(c).add(new T.Vector3(.8,-1.1,.9).normalize().multiplyScalar(s*1.5));camera.near=.01;camera.far=Math.max(1000,s*20);camera.updateProjectionMatrix();controls.update();draw()}
function sectionNormal(){let d=camera.position.distanceTo(controls.target);camera.position.copy(controls.target).add(new T.Vector3().setComponent(axis(),-flip*d));camera.up.set(0,0,1);if(axis()===2)camera.up.set(0,1,0);controls.update();draw()}
function list(){const host=$('parts');host.replaceChildren();const groups=[...new Set(entries.map(e=>e.name))];for(let name of groups){let es=entries.filter(e=>e.name===name),row=document.createElement('label');row.dataset.name=name.toLowerCase();let check=document.createElement('input');check.type='checkbox';check.checked=es.some(e=>e.group.visible);check.onchange=()=>{es.forEach(e=>e.group.visible=check.checked);sectionFaces();draw()};let span=document.createElement('span');span.textContent=name;let btn=document.createElement('button');btn.textContent='Solo';btn.onclick=()=>{entries.forEach(e=>e.group.visible=e.name===name);list();sectionFaces();fit()};row.append(check,span,btn);host.append(row)}filter()}
function filter(){for(let row of $('parts').children)row.style.display=row.dataset.name.includes($('search').value.toLowerCase())?'flex':'none'}
async function load(){const token=++buildToken;$('loading').style.display='block';$('loading').textContent='Loading CAD meshes…';const data=await(await fetch($('product').value+'.json',{cache:'no-store'})).json();if(token!==buildToken)return;
 directContact=data.product!=='max'&&['button-dfa-r5','family-layout-r6','family-layout-r7','clean-enclosures-r8','compact-handheld-r9'].includes(data.revision);$('assemblyView').disabled=!directContact;$('insertion').disabled=!directContact;$('travel').max=directContact?.3+Number($('switchTravel').value):1.6;$('insertion').value=0;
 for(let e of entries){e.mesh.geometry.dispose();e.edge.geometry.dispose();e.mesh.material.dispose();e.edge.material.dispose();e.hidden.material.dispose()}root.clear();entries=[];
 for(let i of data.items){let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(i.vertices.flat(),3));g.setIndex(i.faces.flat());g.computeVertexNormals();let material=new T.MeshStandardMaterial({color:colors[i.material]??0x909daa,roughness:.65,metalness:0,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:1});let mesh=new T.Mesh(g,material),edges=new T.EdgesGeometry(g,24),edge=new T.LineSegments(edges,new T.LineBasicMaterial({color:0x293b47}));let hidden=new T.LineSegments(edges,new T.LineDashedMaterial({color:0x4c7995,transparent:true,opacity:.55,dashSize:.35,gapSize:.2,depthFunc:T.GreaterDepth,depthWrite:false}));hidden.computeLineDistances();hidden.renderOrder=3;let group=new T.Group();group.add(mesh,edge,hidden);root.add(group);let e={mesh,edge,hidden,group,name:i.group??i.name,shell:i.material.startsWith('shell'),source:i,rest:new Float32Array(g.attributes.position.array)};mesh.userData.entry=e;entries.push(e)}
 bounds.setFromObject(root);range();list();sync();fit();$('loading').style.display='none';$('note').textContent=directContact?'DFA prototype: rectangular drafted buttons, flat rear face and closed pogo floor. Insert strip before PCB. Slider covers nominal gap plus selected switch travel; full axial stack-up, overload stops, fatigue and tooling remain unqualified.':data.items.some(i=>i.motion)?'Internal flexure prototype: only original 5mm button faces outside; rail, stops and tips inside. 1.6mm nominal stop travel. +/-0.20mm alignment envelope. Allocated tolerance only; supplier stack-up, tip force, fatigue and dynamic sealing still unqualified.':data.product==='max'?'Clean MAX r8: 43 mm shell, 18.4 mm HAT spacers. Pi access: Ethernet with underside latch relief and USB-C power only. HDMI and USB-A enclosed. Fit prototype.':'Button geometry is the current proposal, not a validated mechanism. Switch reference CAD is seated on PCB Z=7.4; native model offset needs correction. Mini inner flange overlaps PCB (see inspection.json).';if(data.product==='mini')buttonView();$('travel').value=0;resize();$('status').textContent='Ready · dimensions in mm · orange = cut contour';window.viewerReady=true;}
function range(){let a=axis();$('slider').min=bounds.min.getComponent(a)-1;$('slider').max=bounds.max.getComponent(a)+1;}
function buttonView(){if($('product').value==='max')return;let es=entries.filter(e=>e.source.motion==='rigid');if(!es.length)es=entries.filter(e=>e.source.material==='button');let e=es[0];if(!e)return;let b=new T.Box3().setFromObject(e.mesh),c=b.getCenter(new T.Vector3());$('axis').value='X';$('section').checked=true;flip=1;$('position').value=c.x;$('slider').value=c.x;range();controls.target.set(c.x,.5,c.z);camera.up.set(0,0,1);camera.position.set(c.x-23,-15,c.z+4.9);sync();controls.update();draw()}
// Intersect triangles, stitch closed loops, triangulate nested loops as holes.
function sectionFaces(){for(let o of cutGroup.children){o.geometry.dispose();o.material.dispose()}cutGroup.clear();if(!$('section').checked){draw();return}const a=axis(),uv=[[1,2],[0,2],[0,1]][a],p=+$('position').value;
 for(let e of entries){if(!e.group.visible)continue;let g=e.mesh.geometry,arr=g.attributes.position.array,idx=g.index.array,segments=[],point=k=>[arr[k*3],arr[k*3+1],arr[k*3+2]];
 for(let t=0;t<idx.length;t+=3){let vs=[point(idx[t]),point(idx[t+1]),point(idx[t+2])],hits=[];for(let j=0;j<3;j++){let u=vs[j],v=vs[(j+1)%3],du=u[a]-p,dv=v[a]-p;if((du<0&&dv>=0)||(dv<0&&du>=0)){let f=du/(du-dv);hits.push(u.map((x,k)=>x+(v[k]-x)*f))}}if(hits.length===2&&new T.Vector3(...hits[0]).distanceTo(new T.Vector3(...hits[1]))>1e-7)segments.push(hits)}
 if(!segments.length)continue;let lineGeo=new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(segments.flat(2),3));let line=new T.LineSegments(lineGeo,new T.LineBasicMaterial({color:0xee7d22,depthTest:false}));line.renderOrder=5;cutGroup.add(line);if(!$('caps').checked)continue;
 const key=v=>v.map(x=>Math.round(x*10000)).join(','),adj=new Map();segments.forEach((seg,i)=>seg.forEach(v=>{let k=key(v);if(!adj.has(k))adj.set(k,[]);adj.get(k).push(i)}));let used=new Set(),loops=[];
 segments.forEach((seg,start)=>{if(used.has(start))return;let loop=[seg[0]],cur=seg[1];used.add(start);let n=0;while(key(cur)!==key(loop[0])&&n++<segments.length){loop.push(cur);let next=(adj.get(key(cur))??[]).find(i=>!used.has(i));if(next===undefined)break;used.add(next);let s=segments[next];cur=key(s[0])===key(cur)?s[1]:s[0]}if(key(cur)===key(loop[0])&&loop.length>=3)loops.push(loop.map(v=>new T.Vector2(v[uv[0]],v[uv[1]])))});
 const area=pts=>Math.abs(T.ShapeUtils.area(pts)),inside=(pt,poly)=>{let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let x=poly[i],y=poly[j];if((x.y>pt.y)!==(y.y>pt.y)&&pt.x<(y.x-x.x)*(pt.y-x.y)/(y.y-x.y)+x.x)c=!c}return c};loops.sort((x,y)=>area(y)-area(x));let nodes=[];
 for(let pts of loops){let parent=-1;for(let j=nodes.length-1;j>=0;j--)if(inside(pts[0],nodes[j].pts)){parent=j;break}let depth=parent<0?0:nodes[parent].depth+1;nodes.push({pts,parent,depth})}
 nodes.forEach((node,j)=>{if(node.depth%2)return;let shape=new T.Shape(node.pts);nodes.filter(n=>n.parent===j&&n.depth%2).forEach(n=>shape.holes.push(new T.Path(n.pts)));let geo=new T.ShapeGeometry(shape),pos=geo.attributes.position;for(let k=0;k<pos.count;k++){let v=[0,0,0];v[a]=p;v[uv[0]]=pos.getX(k);v[uv[1]]=pos.getY(k);pos.setXYZ(k,...v)}geo.computeVertexNormals();let cap=new T.Mesh(geo,new T.MeshBasicMaterial({color:e.mesh.material.color.clone().lerp(new T.Color(0xffd59d),.4),side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));cutGroup.add(cap)});
 }draw()}
$('product').onchange=()=>load().catch(fail);$('fit').onclick=fit;$('buttonView').onclick=buttonView;$('side').onclick=sectionNormal;$('iso').onclick=fit;$('search').oninput=filter;
for(let id of ['edges','hidden','ghost','section','caps','plane'])$(id).onchange=sync;
$('axis').onchange=()=>{range();$('position').value=bounds.getCenter(new T.Vector3()).getComponent(axis());$('slider').value=$('position').value;sync()};$('slider').oninput=()=>{$('position').value=$('slider').value;sync()};$('position').oninput=()=>{$('slider').value=$('position').value;sync()};$('flip').onclick=()=>{flip*=-1;sync()};$('showAll').onclick=()=>{$('insertion').value=0;moveButtons();entries.forEach(e=>e.group.visible=true);list();sectionFaces();draw()};$('hideShell').onclick=()=>{entries.filter(e=>e.shell).forEach(e=>e.group.visible=false);list();sectionFaces();draw()};
let ray=new T.Raycaster(),pointer=new T.Vector2();renderer.domElement.addEventListener('pointermove',ev=>{let r=renderer.domElement.getBoundingClientRect();pointer.set((ev.clientX-r.left)/r.width*2-1,-(ev.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);let hit=ray.intersectObjects(entries.filter(e=>e.group.visible).map(e=>e.mesh)).find(h=>!$('section').checked||clip.distanceToPoint(h.point)>=0);selected=hit?.object.userData.entry;$('status').textContent=hit?`${selected.name} · ${hit.point.toArray().map(x=>x.toFixed(2)).join(', ')} mm`:'Orbit · pan · zoom | orange = cut contour'});
renderer.domElement.addEventListener('click',()=>{if(selected){$('status').textContent=selected.name+' — '+(selected.source.note??'Reviewed CAD mesh')}});
function download(blob,name){let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('snapshot').onclick=()=>{draw();renderer.domElement.toBlob(b=>download(b,'splanc-section.png'));download(new Blob([JSON.stringify({product:$('product').value,insertion:+$('insertion').value,travel:+$('travel').value,pressButton:$('pressButton').value,switchTravel:+$('switchTravel').value,section:$('section').checked,axis:$('axis').value,position:+$('position').value,flip,camera:camera.position.toArray(),target:controls.target.toArray(),hidden:entries.filter(e=>!e.group.visible).map(e=>e.name)},null,2)],{type:'application/json'}),'splanc-section.json')};
function fail(err){$('loading').style.display='block';$('loading').textContent='Viewer error: '+err.message;console.error(err)}window.addEventListener('error',ev=>fail(ev.error??new Error(ev.message)));resize();load().catch(fail);

function moveButtons(){let st=+$('switchTravel').value;if(directContact){$('travel').max=.3+st;$('travel').value=Math.min(+$('travel').value,.3+st)}let d=+$('travel').value,insert=+$('insertion').value;$('insertionValue').textContent=insert.toFixed(1)+' mm'; $('travelValue').textContent=d.toFixed(2)+' mm';
 for(let e of entries){let isStrip=e.source.group==='Flat-backed button strip',m=e.source.motion??(isStrip?'frame':null);if(!m)continue;let d=($('pressButton').value==='all'||e.source.button_index===+$('pressButton').value)?+$('travel').value:0;let pos=e.mesh.geometry.attributes.position,src=e.rest;let cx=new T.Box3().setFromBufferAttribute(new T.BufferAttribute(src,3)).getCenter(new T.Vector3()).x;
 for(let k=0;k<pos.count;k++){let x=src[k*3],y=src[k*3+1],z=src[k*3+2];
 if(m==='rigid')y+=d;
 if(m==='spring'){let f=T.MathUtils.clamp((z-e.source.anchor_z)/(e.source.moving_z-e.source.anchor_z),0,1);y+=d*f*f*(3-2*f)}
 if(m==='tip'){let start=e.source.tip_start+d,end=Math.min(e.source.tip_end+d,1.75+st),f=(y-e.source.tip_start)/(e.source.tip_end-e.source.tip_start);y=start+f*(end-start);let bulge=Math.sqrt((e.source.tip_end-e.source.tip_start)/(end-start));x=cx+(x-cx)*bulge;z=9.1+(z-9.1)*bulge;}
 if(m==='actuator')y+=Math.min(st,Math.max(0,d-.30));
 if(isStrip)y+=insert;pos.setXYZ(k,x,y,z)}pos.needsUpdate=true;e.mesh.geometry.computeVertexNormals();e.edge.geometry.dispose();e.edge.geometry=new T.EdgesGeometry(e.mesh.geometry,24);e.hidden.geometry=e.edge.geometry;e.hidden.computeLineDistances();}
 clearTimeout(timer);timer=setTimeout(sectionFaces,60);draw();}
$('insertion').oninput=moveButtons;$('assemblyView').onclick=()=>{entries.forEach(e=>e.group.visible=e.source.name==='base'||e.source.group==='Flat-backed button strip');$('section').checked=false;$('travel').value=0;$('insertion').value=12;moveButtons();list();sync();fit()};
$('pressButton').onchange=moveButtons;$('travel').oninput=moveButtons;$('switchTravel').onchange=moveButtons;
$('userView').onclick=async()=>{let v=await(await fetch('user-view.json')).json();if($('product').value!==v.product){$('product').value=v.product;await load()}$('section').checked=v.section;$('axis').value=v.axis;$('position').value=v.position;flip=v.flip;range();$('slider').value=v.position;camera.position.fromArray(v.camera);controls.target.fromArray(v.target);camera.up.set(0,0,1);entries.forEach(e=>e.group.visible=!v.hidden.includes(e.name));list();$('insertion').value=v.insertion??0;$('travel').value=v.travel??0;$('pressButton').value=v.pressButton??'all';$('switchTravel').value=v.switchTravel??.2;moveButtons();sync();controls.update();draw()};
