#!/usr/bin/env python3
"""Embed the built web bundle (//web:dist) as a C asset table for the player.

Walks the dist directory, gzips each file, and emits a single translation unit
(web_assets.cpp) declaring a `kWebAssets[]` table of {path, data, len, ctype,
gzip}. The ESP's :80 WebServer serves these from flash (.rodata) so a phone can
open http://<player>/ and get the control UI over plain HTTP — same-origin
ws://<player>:81/ws, no TLS and no mixed-content wall.

Only the control UI needs to ship: the dist bundle is ~70 KB gzipped and holds
no wasm (the solver/pulse wasm is added only at `//web:serve` time), so the
whole tree fits comfortably in the 3 MB factory app slot.

Usage: embed_web.py <dist_dir> <out_cpp>
"""

import gzip
import os
import sys

# Extension -> Content-Type. Anything unlisted falls back to octet-stream; the
# browser still runs module scripts as long as .js maps to a JS type.
CTYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".wasm": "application/wasm",
    ".map": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
    ".woff2": "font/woff2",
    ".txt": "text/plain; charset=utf-8",
}


def ctype_for(path: str) -> str:
    _, ext = os.path.splitext(path)
    return CTYPES.get(ext.lower(), "application/octet-stream")


def c_bytes(data: bytes) -> str:
    # 16 bytes per line keeps the generated source readable and the compiler
    # happy (no absurdly long lines).
    out = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        out.append("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write("usage: embed_web.py <dist_dir> <out_cpp>\n")
        return 2
    dist, out_cpp = sys.argv[1], sys.argv[2]

    files = []
    for root, _, names in os.walk(dist):
        for name in sorted(names):
            abspath = os.path.join(root, name)
            # URL path is the dist-relative path with a leading slash, POSIX
            # separators (the browser requests "/assets/index-<hash>.js").
            rel = os.path.relpath(abspath, dist).replace(os.sep, "/")
            files.append((f"/{rel}", abspath))
    files.sort()

    lines = [
        "// Generated by firmware/webapp/embed_web.py — do not edit.",
        '#include "firmware/webapp/web_assets.h"',
        "",
    ]
    table = []
    for idx, (urlpath, abspath) in enumerate(files):
        with open(abspath, "rb") as f:
            raw = f.read()
        gz = gzip.compress(raw, 9)
        # Only keep the gzip if it actually helps; tiny/already-compressed
        # files can grow, in which case serve them raw.
        use_gz = len(gz) < len(raw)
        blob = gz if use_gz else raw
        lines.append(f"static const unsigned char kAsset{idx}[] = {{")
        lines.append(c_bytes(blob))
        lines.append("};")
        lines.append("")
        table.append(
            f'  {{"{urlpath}", kAsset{idx}, sizeof(kAsset{idx}), '
            f'"{ctype_for(urlpath)}", {"true" if use_gz else "false"}}},'
        )

    lines.append("const WebAsset kWebAssets[] = {")
    lines.extend(table)
    lines.append("};")
    lines.append(f"const size_t kWebAssetCount = {len(files)};")
    lines.append("")

    with open(out_cpp, "w") as f:
        f.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
