// The built web bundle (//web:dist) embedded as flash assets, served by the
// player's :80 WebServer. Table is generated by embed_web.py into
// web_assets.cpp; this header is the stable declaration the server includes.
#pragma once

#include <stddef.h>

struct WebAsset {
  const char* path;         // request path, e.g. "/assets/index-<hash>.js"
  const unsigned char* data;  // file bytes (gzip-compressed when `gzip`)
  size_t len;
  const char* ctype;        // Content-Type header value
  bool gzip;                // send Content-Encoding: gzip when true
};

extern const WebAsset kWebAssets[];
extern const size_t kWebAssetCount;
