"""LED Mapper protocol — code generator.

Regenerates the TypeScript types (`ts/generated/index.ts`) and Pydantic v2
models (`python/ledmapper_protocol/_generated.py`) from the JSON Schema set
under `schemas/`.

Usage:
    # Default: write into the in-tree source paths.
    python3 shared/protocol/codegen.py

    # CI / Bazel-driven: refuse to write, fail on stale.
    python3 shared/protocol/codegen.py --check

    # Bazel genrule: write generated files to specific output paths and read
    # schemas from a specific directory. Both paths are required together.
    python3 shared/protocol/codegen.py \\
        --schema-dir <path> \\
        --ts-out <path-to-index.ts> \\
        --py-out <path-to-_generated.py>

The generator is intentionally narrow: it understands exactly the schema
shapes used by this protocol (§7 of the design doc). It is NOT a general
JSON-Schema-to-X tool. If you add a new shape to a schema, extend the
emitter rather than reaching for an external dependency — the protocol is
small enough that a focused generator is cheaper than fighting a generic
one.

The generator is deterministic: re-running with no schema changes produces
byte-identical output, which is what `--check` verifies and what the Bazel
genrule depends on for caching.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent
DEFAULT_SCHEMA_DIR = ROOT / "schemas"
DEFAULT_TS_OUT = ROOT / "ts" / "generated" / "index.ts"
DEFAULT_PY_OUT = ROOT / "python" / "ledmapper_protocol" / "_generated.py"


# ---------------------------------------------------------------------------
# Schema loading + sanity checks
# ---------------------------------------------------------------------------


def load_schemas(schema_dir: Path) -> dict[str, dict]:
    schemas: dict[str, dict] = {}
    for path in sorted(schema_dir.glob("*.json")):
        with path.open() as f:
            schemas[path.stem] = json.load(f)
    expected = {
        "detection_record",
        "code_params",
        "output_map",
        "client_messages",
        "server_messages",
    }
    missing = expected - schemas.keys()
    if missing:
        raise RuntimeError(f"Missing schema files in {schema_dir}: {sorted(missing)}")
    return schemas


def validate_schemas(schemas: dict[str, dict]) -> None:
    """Cheap consistency checks. The schemas themselves are the contract;
    these checks catch obvious drift between the docs and the schemas."""
    cp = schemas["code_params"]
    assert set(cp["required"]) == {
        "ledCount",
        "bits",
        "encoding",
        "bitPeriodMs",
        "syncPattern",
        "cycleFrames",
    }, "code_params required fields drifted from §7.6"
    dr = schemas["detection_record"]
    assert set(dr["required"]) == {
        "ledId",
        "tCaptureMs",
        "u",
        "v",
        "imgW",
        "imgH",
        "K",
        "pose",
        "confidence",
    }, "detection_record required fields drifted from §7.4"
    for name in ("client_messages", "server_messages"):
        sch = schemas[name]
        for variant in sch["$defs"].values():
            assert "type" in variant.get("properties", {}), (
                f"{name}: variant missing 'type' discriminator"
            )


# ---------------------------------------------------------------------------
# TypeScript emitter
# ---------------------------------------------------------------------------


TS_HEADER = """// LED Mapper protocol types.
//
// AUTO-GENERATED by shared/protocol/codegen.py from shared/protocol/schemas/*.json.
// Do not edit by hand. Regenerate via:  bazel build //shared/protocol:codegen
//
// Source of truth is the JSON Schema set under shared/protocol/schemas/.
// See design doc §7 for the contracts.
"""


def emit_typescript(schemas: dict[str, dict]) -> str:
    cp = schemas["code_params"]
    encoding_values = cp["properties"]["encoding"]["enum"]
    sync_values = cp["properties"]["syncPattern"]["enum"]
    omap = schemas["output_map"]
    units_values = omap["properties"]["units"]["enum"]
    frame_values = omap["properties"]["frame"]["enum"]

    lines: list[str] = [TS_HEADER]
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Core building blocks")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("/** Camera intrinsics for a single frame: [fx, fy, cx, cy]. */")
    lines.append("export type Intrinsics = [number, number, number, number];\n")
    lines.append("/** 3D position [x, y, z] in meters. */")
    lines.append("export type Vec3 = [number, number, number];\n")
    lines.append("/** Quaternion [x, y, z, w]. */")
    lines.append("export type Quat = [number, number, number, number];\n")
    lines.append("/** Camera pose in the WebXR session reference space. */")
    lines.append("export interface Pose {")
    lines.append("  p: Vec3;")
    lines.append("  q: Quat;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// DetectionRecord (§7.4)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface DetectionRecord {")
    lines.append("  ledId: number;")
    lines.append("  /** Phone monotonic clock at frame capture, in milliseconds. */")
    lines.append("  tCaptureMs: number;")
    lines.append("  /** Sub-pixel centroid x (origin top-left). */")
    lines.append("  u: number;")
    lines.append("  /** Sub-pixel centroid y (origin top-left). */")
    lines.append("  v: number;")
    lines.append("  imgW: number;")
    lines.append("  imgH: number;")
    lines.append("  K: Intrinsics;")
    lines.append("  pose: Pose;")
    lines.append("  /** Decoder confidence in [0, 1]. */")
    lines.append("  confidence: number;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// CodeParams (§7.6)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append(
        "export type Encoding = " + " | ".join(f'"{v}"' for v in encoding_values) + ";"
    )
    lines.append(
        "export type SyncPattern = " + " | ".join(f'"{v}"' for v in sync_values) + ";\n"
    )
    lines.append("export interface CodeParams {")
    lines.append("  ledCount: number;")
    lines.append("  /** ceil(log2(ledCount)) */")
    lines.append("  bits: number;")
    lines.append("  encoding: Encoding;")
    lines.append("  /** Hold time per bit frame, in milliseconds. */")
    lines.append("  bitPeriodMs: number;")
    lines.append("  syncPattern: SyncPattern;")
    lines.append("  /** 2 (sync delimiter) + bits */")
    lines.append("  cycleFrames: number;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// OutputMap (§7.5)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface LedEntry {")
    lines.append("  id: number;")
    lines.append("  xyz: Vec3;")
    lines.append("  confidence: number;")
    lines.append("  nViews: number;")
    lines.append("  rmsReprojPx: number;")
    lines.append("  parallaxDeg: number;")
    lines.append("}\n")
    lines.append("export interface OutputMapStats {")
    lines.append("  rmsReprojPxGlobal: number;")
    lines.append("  medianParallaxDeg: number;")
    lines.append("}\n")
    lines.append("export interface OutputMap {")
    lines.append("  mapId: string;")
    lines.append("  /** ISO-8601 timestamp. */")
    lines.append("  createdAt: string;")
    units_ts = " | ".join('"' + v + '"' for v in units_values)
    frame_ts = " | ".join('"' + v + '"' for v in frame_values)
    lines.append(f"  units: {units_ts};")
    lines.append(f"  frame: {frame_ts};")
    lines.append("  ledCount: number;")
    lines.append("  leds: LedEntry[];")
    lines.append("  unmapped: number[];")
    lines.append("  stats: OutputMapStats;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Client -> Server messages (§7.1)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface HelloMessage {")
    lines.append('  type: "hello";')
    lines.append("  client: string;")
    lines.append("  appVersion: string;")
    lines.append("}\n")
    lines.append("export interface TimeSyncPingMessage {")
    lines.append('  type: "time_sync_ping";')
    lines.append("  /** Phone clock at send, in milliseconds. */")
    lines.append("  t0: number;")
    lines.append("}\n")
    lines.append("export interface StartMappingOptions {")
    lines.append("  ledCount: number;")
    lines.append("}\n")
    lines.append("export interface StartMappingMessage {")
    lines.append('  type: "start_mapping";')
    lines.append("  options: StartMappingOptions;")
    lines.append("}\n")
    lines.append("export interface StopMappingMessage {")
    lines.append('  type: "stop_mapping";')
    lines.append("}\n")
    lines.append("export interface DetectionsMessage {")
    lines.append('  type: "detections";')
    lines.append("  batch: DetectionRecord[];")
    lines.append("}\n")
    lines.append("export interface GetStatusMessage {")
    lines.append('  type: "get_status";')
    lines.append("}\n")
    lines.append("export type ClientMessage =")
    lines.append("  | HelloMessage")
    lines.append("  | TimeSyncPingMessage")
    lines.append("  | StartMappingMessage")
    lines.append("  | StopMappingMessage")
    lines.append("  | DetectionsMessage")
    lines.append("  | GetStatusMessage;\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Server -> Client messages (§7.2)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface WelcomeMessage {")
    lines.append('  type: "welcome";')
    lines.append("  sessionId: string;")
    lines.append("  codeParams: CodeParams;")
    lines.append("}\n")
    lines.append("export interface TimeSyncPongMessage {")
    lines.append('  type: "time_sync_pong";')
    lines.append("  /** Echoed phone clock at original send, in milliseconds. */")
    lines.append("  t0: number;")
    lines.append("  /** Server clock at receive of ping, in milliseconds. */")
    lines.append("  t1: number;")
    lines.append("  /** Server clock at send of pong, in milliseconds. */")
    lines.append("  t2: number;")
    lines.append("}\n")
    lines.append("export interface MappingStartedMessage {")
    lines.append('  type: "mapping_started";')
    lines.append("  /** Server-clock time of the start of a known cycle, in milliseconds. */")
    lines.append("  patternClockEpoch: number;")
    lines.append("  codeParams: CodeParams;")
    lines.append("}\n")
    lines.append("export interface StatusMessage {")
    lines.append('  type: "status";')
    lines.append("  identified: number;")
    lines.append("  total: number;")
    lines.append("  lowParallax: number;")
    lines.append("}\n")
    lines.append("export interface ResultReadyMessage {")
    lines.append('  type: "result_ready";')
    lines.append("  mapId: string;")
    lines.append("}\n")
    lines.append("export interface ErrorMessage {")
    lines.append('  type: "error";')
    lines.append("  code: string;")
    lines.append("  message: string;")
    lines.append("}\n")
    lines.append("export type ServerMessage =")
    lines.append("  | WelcomeMessage")
    lines.append("  | TimeSyncPongMessage")
    lines.append("  | MappingStartedMessage")
    lines.append("  | StatusMessage")
    lines.append("  | ResultReadyMessage")
    lines.append("  | ErrorMessage;")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Python (Pydantic v2) emitter
# ---------------------------------------------------------------------------


PY_HEADER = '''"""LED Mapper protocol — Pydantic v2 models (generated).

AUTO-GENERATED by shared/protocol/codegen.py from shared/protocol/schemas/*.json.
Do not edit by hand. Regenerate via:  bazel build //shared/protocol:codegen

Source of truth is the JSON Schema set under shared/protocol/schemas/.
See design doc §7 for the contracts.

All models set `extra='forbid'` so unknown fields fail loudly — the protocol
package exists to surface contract drift, not to paper over it.

This module is imported and re-exported from `ledmapper_protocol/__init__.py`,
which is the public surface for Python consumers.
"""

from __future__ import annotations

from typing import Annotated, List, Literal, Tuple, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel
'''


def _literal(values: Iterable[str]) -> str:
    return "Literal[" + ", ".join(f'"{v}"' for v in values) + "]"


def emit_python(schemas: dict[str, dict]) -> str:
    cp = schemas["code_params"]
    encoding_values = cp["properties"]["encoding"]["enum"]
    sync_values = cp["properties"]["syncPattern"]["enum"]
    omap = schemas["output_map"]
    units_values = omap["properties"]["units"]["enum"]
    frame_values = omap["properties"]["frame"]["enum"]

    out: list[str] = [PY_HEADER]
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Type aliases for the small fixed-arity arrays.")
    out.append("# pydantic v2 enforces these as fixed-length tuples when typed as Tuple[...].")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("Vec3 = Tuple[float, float, float]")
    out.append("Quat = Tuple[float, float, float, float]")
    out.append("Intrinsics = Tuple[float, float, float, float]")
    out.append("")
    out.append("")
    out.append("class _StrictModel(BaseModel):")
    out.append('    """Common base: forbid unknown fields across the whole protocol."""')
    out.append("")
    out.append('    model_config = ConfigDict(extra="forbid")')
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Pose / DetectionRecord (§7.4)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class Pose(_StrictModel):")
    out.append("    p: Vec3")
    out.append("    q: Quat")
    out.append("")
    out.append("")
    out.append("class DetectionRecord(_StrictModel):")
    out.append("    ledId: int = Field(ge=0)")
    out.append("    tCaptureMs: float")
    out.append("    u: float")
    out.append("    v: float")
    out.append("    imgW: int = Field(ge=1)")
    out.append("    imgH: int = Field(ge=1)")
    out.append("    K: Intrinsics")
    out.append("    pose: Pose")
    out.append("    confidence: float = Field(ge=0.0, le=1.0)")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# CodeParams (§7.6)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append(f"Encoding = {_literal(encoding_values)}")
    out.append(f"SyncPattern = {_literal(sync_values)}")
    out.append("")
    out.append("")
    out.append("class CodeParams(_StrictModel):")
    out.append("    ledCount: int = Field(ge=1)")
    out.append("    bits: int = Field(ge=1)")
    out.append("    encoding: Encoding")
    out.append("    bitPeriodMs: float = Field(gt=0.0)")
    out.append("    syncPattern: SyncPattern")
    out.append("    cycleFrames: int = Field(ge=3)")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# OutputMap (§7.5)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class LedEntry(_StrictModel):")
    out.append("    id: int = Field(ge=0)")
    out.append("    xyz: Vec3")
    out.append("    confidence: float = Field(ge=0.0, le=1.0)")
    out.append("    nViews: int = Field(ge=0)")
    out.append("    rmsReprojPx: float = Field(ge=0.0)")
    out.append("    parallaxDeg: float = Field(ge=0.0)")
    out.append("")
    out.append("")
    out.append("class OutputMapStats(_StrictModel):")
    out.append("    rmsReprojPxGlobal: float = Field(ge=0.0)")
    out.append("    medianParallaxDeg: float = Field(ge=0.0)")
    out.append("")
    out.append("")
    out.append("class OutputMap(_StrictModel):")
    out.append("    mapId: str")
    out.append("    createdAt: str")
    out.append(f"    units: {_literal(units_values)}")
    out.append(f"    frame: {_literal(frame_values)}")
    out.append("    ledCount: int = Field(ge=0)")
    out.append("    leds: List[LedEntry]")
    out.append("    unmapped: List[int]")
    out.append("    stats: OutputMapStats")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Client -> Server messages (§7.1)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class HelloMessage(_StrictModel):")
    out.append('    type: Literal["hello"]')
    out.append("    client: str")
    out.append("    appVersion: str")
    out.append("")
    out.append("")
    out.append("class TimeSyncPingMessage(_StrictModel):")
    out.append('    type: Literal["time_sync_ping"]')
    out.append("    t0: float")
    out.append("")
    out.append("")
    out.append("class StartMappingOptions(_StrictModel):")
    out.append("    ledCount: int = Field(ge=1)")
    out.append("")
    out.append("")
    out.append("class StartMappingMessage(_StrictModel):")
    out.append('    type: Literal["start_mapping"]')
    out.append("    options: StartMappingOptions")
    out.append("")
    out.append("")
    out.append("class StopMappingMessage(_StrictModel):")
    out.append('    type: Literal["stop_mapping"]')
    out.append("")
    out.append("")
    out.append("class DetectionsMessage(_StrictModel):")
    out.append('    type: Literal["detections"]')
    out.append("    batch: List[DetectionRecord]")
    out.append("")
    out.append("")
    out.append("class GetStatusMessage(_StrictModel):")
    out.append('    type: Literal["get_status"]')
    out.append("")
    out.append("")
    out.append("ClientMessageInner = Annotated[")
    out.append("    Union[")
    out.append("        HelloMessage,")
    out.append("        TimeSyncPingMessage,")
    out.append("        StartMappingMessage,")
    out.append("        StopMappingMessage,")
    out.append("        DetectionsMessage,")
    out.append("        GetStatusMessage,")
    out.append("    ],")
    out.append('    Field(discriminator="type"),')
    out.append("]")
    out.append("")
    out.append("")
    out.append("class ClientMessage(RootModel[ClientMessageInner]):")
    out.append('    """Discriminated union of all client (phone) -> server (Pi) messages."""')
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Server -> Client messages (§7.2)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class WelcomeMessage(_StrictModel):")
    out.append('    type: Literal["welcome"]')
    out.append("    sessionId: str")
    out.append("    codeParams: CodeParams")
    out.append("")
    out.append("")
    out.append("class TimeSyncPongMessage(_StrictModel):")
    out.append('    type: Literal["time_sync_pong"]')
    out.append("    t0: float")
    out.append("    t1: float")
    out.append("    t2: float")
    out.append("")
    out.append("")
    out.append("class MappingStartedMessage(_StrictModel):")
    out.append('    type: Literal["mapping_started"]')
    out.append("    patternClockEpoch: float")
    out.append("    codeParams: CodeParams")
    out.append("")
    out.append("")
    out.append("class StatusMessage(_StrictModel):")
    out.append('    type: Literal["status"]')
    out.append("    identified: int = Field(ge=0)")
    out.append("    total: int = Field(ge=0)")
    out.append("    lowParallax: int = Field(ge=0)")
    out.append("")
    out.append("")
    out.append("class ResultReadyMessage(_StrictModel):")
    out.append('    type: Literal["result_ready"]')
    out.append("    mapId: str")
    out.append("")
    out.append("")
    out.append("class ErrorMessage(_StrictModel):")
    out.append('    type: Literal["error"]')
    out.append("    code: str")
    out.append("    message: str")
    out.append("")
    out.append("")
    out.append("ServerMessageInner = Annotated[")
    out.append("    Union[")
    out.append("        WelcomeMessage,")
    out.append("        TimeSyncPongMessage,")
    out.append("        MappingStartedMessage,")
    out.append("        StatusMessage,")
    out.append("        ResultReadyMessage,")
    out.append("        ErrorMessage,")
    out.append("    ],")
    out.append('    Field(discriminator="type"),')
    out.append("]")
    out.append("")
    out.append("")
    out.append("class ServerMessage(RootModel[ServerMessageInner]):")
    out.append('    """Discriminated union of all server (Pi) -> client (phone) messages."""')
    out.append("")
    out.append("")
    out.append("__all__ = [")
    for name in [
        "Vec3",
        "Quat",
        "Intrinsics",
        "Pose",
        "DetectionRecord",
        "Encoding",
        "SyncPattern",
        "CodeParams",
        "LedEntry",
        "OutputMapStats",
        "OutputMap",
        "HelloMessage",
        "TimeSyncPingMessage",
        "StartMappingOptions",
        "StartMappingMessage",
        "StopMappingMessage",
        "DetectionsMessage",
        "GetStatusMessage",
        "ClientMessage",
        "WelcomeMessage",
        "TimeSyncPongMessage",
        "MappingStartedMessage",
        "StatusMessage",
        "ResultReadyMessage",
        "ErrorMessage",
        "ServerMessage",
    ]:
        out.append(f'    "{name}",')
    out.append("]")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if generated outputs are stale, instead of writing.",
    )
    parser.add_argument(
        "--schema-dir",
        type=Path,
        default=None,
        help="Directory containing *.json schema files. Default: schemas/ next to this script.",
    )
    parser.add_argument(
        "--ts-out",
        type=Path,
        default=None,
        help="Output path for the generated TypeScript file. Default: ts/generated/index.ts.",
    )
    parser.add_argument(
        "--py-out",
        type=Path,
        default=None,
        help="Output path for the generated Pydantic file. Default: python/ledmapper_protocol/_generated.py.",
    )
    args = parser.parse_args()

    schema_dir = args.schema_dir if args.schema_dir is not None else DEFAULT_SCHEMA_DIR
    ts_out = args.ts_out if args.ts_out is not None else DEFAULT_TS_OUT
    py_out = args.py_out if args.py_out is not None else DEFAULT_PY_OUT

    schemas = load_schemas(schema_dir)
    validate_schemas(schemas)

    ts_text = emit_typescript(schemas)
    py_text = emit_python(schemas)

    targets = [(ts_out, ts_text), (py_out, py_text)]

    if args.check:
        stale: list[Path] = []
        for path, expected in targets:
            actual = path.read_text() if path.exists() else ""
            if actual != expected:
                stale.append(path)
        if stale:
            for p in stale:
                print(f"STALE: {p}", file=sys.stderr)
            print(
                "Run `python3 shared/protocol/codegen.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print("All generated files are up to date.")
        return 0

    for path, text in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        try:
            display = path.relative_to(ROOT.parent.parent)
        except ValueError:
            display = path
        print(f"wrote {display}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
