"""LED Mapper protocol — code generator.

Regenerates the TypeScript types (`ts/generated/index.ts`) and Pydantic v2
models (`python/ledmapper_protocol/_generated.py`) from the JSON Schema set
under `schemas/`.

Usage:
    # Default: write into the in-tree source paths.
    python3 shared/protocol/codegen.py

    # CI / Bazel-driven: refuse to write, fail on stale.
    python3 shared/protocol/codegen.py --check

    # Bazel genrule: write generated files to specific output paths and read
    # schemas from a specific directory. Both paths are required together.
    python3 shared/protocol/codegen.py \\
        --schema-dir <path> \\
        --ts-out <path-to-index.ts> \\
        --py-out <path-to-_generated.py>

The generator is intentionally narrow: it understands exactly the schema
shapes used by this protocol (§7 of the design doc). It is NOT a general
JSON-Schema-to-X tool. If you add a new shape to a schema, extend the
emitter rather than reaching for an external dependency — the protocol is
small enough that a focused generator is cheaper than fighting a generic
one.

The generator is deterministic: re-running with no schema changes produces
byte-identical output, which is what `--check` verifies and what the Bazel
genrule depends on for caching.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent
DEFAULT_SCHEMA_DIR = ROOT / "schemas"
DEFAULT_TS_OUT = ROOT / "ts" / "generated" / "index.ts"
DEFAULT_PY_OUT = ROOT / "python" / "ledmapper_protocol" / "_generated.py"


# ---------------------------------------------------------------------------
# Schema loading + sanity checks
# ---------------------------------------------------------------------------


def load_schemas(schema_dir: Path) -> dict[str, dict]:
    schemas: dict[str, dict] = {}
    for path in sorted(schema_dir.glob("*.json")):
        with path.open() as f:
            schemas[path.stem] = json.load(f)
    expected = {
        "detection_record",
        "code_params",
        "output_map",
        "topology",
        "playback_params",
        "client_messages",
        "server_messages",
    }
    missing = expected - schemas.keys()
    if missing:
        raise RuntimeError(f"Missing schema files in {schema_dir}: {sorted(missing)}")
    return schemas


def validate_schemas(schemas: dict[str, dict]) -> None:
    """Cheap consistency checks. The schemas themselves are the contract;
    these checks catch obvious drift between the docs and the schemas."""
    cp = schemas["code_params"]
    assert set(cp["required"]) == {
        "ledCount",
        "bits",
        "encoding",
        "symbols",
        "bitPeriodMs",
        "syncPattern",
        "cycleFrames",
    }, "code_params required fields drifted from §7.6"
    dr = schemas["detection_record"]
    assert set(dr["required"]) == {
        "ledId",
        "tCaptureMs",
        "u",
        "v",
        "imgW",
        "imgH",
        "K",
        "pose",
        "confidence",
    }, "detection_record required fields drifted from §7.4"
    for name in ("client_messages", "server_messages"):
        sch = schemas[name]
        # Only the oneOf members are message variants needing a discriminator;
        # other $defs (e.g. ExposureStats) are plain shared structs.
        for ref in sch["oneOf"]:
            variant_name = ref["$ref"].rsplit("/", 1)[-1]
            variant = sch["$defs"][variant_name]
            assert "type" in variant.get(
                "properties", {}
            ), f"{name}: variant {variant_name} missing 'type' discriminator"


# ---------------------------------------------------------------------------
# TypeScript emitter
# ---------------------------------------------------------------------------


TS_HEADER = """// LED Mapper protocol types.
//
// AUTO-GENERATED by shared/protocol/codegen.py from shared/protocol/schemas/*.json.
// Do not edit by hand. Regenerate via:  bazel build //shared/protocol:codegen
//
// Source of truth is the JSON Schema set under shared/protocol/schemas/.
// See design doc §7 for the contracts.
"""


def emit_typescript(schemas: dict[str, dict]) -> str:
    cp = schemas["code_params"]
    encoding_values = cp["properties"]["encoding"]["enum"]
    sync_values = cp["properties"]["syncPattern"]["enum"]
    fec_values = cp["properties"]["fec"]["enum"]
    omap = schemas["output_map"]
    units_values = omap["properties"]["units"]["enum"]
    frame_values = omap["properties"]["frame"]["enum"]

    lines: list[str] = [TS_HEADER]
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Core building blocks")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("/** Camera intrinsics for a single frame: [fx, fy, cx, cy]. */")
    lines.append("export type Intrinsics = [number, number, number, number];\n")
    lines.append("/** 3D position [x, y, z] in meters. */")
    lines.append("export type Vec3 = [number, number, number];\n")
    lines.append("/** Quaternion [x, y, z, w]. */")
    lines.append("export type Quat = [number, number, number, number];\n")
    lines.append("/** Camera pose in the WebXR session reference space. */")
    lines.append("export interface Pose {")
    lines.append("  p: Vec3;")
    lines.append("  q: Quat;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// DetectionRecord (§7.4)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface DetectionRecord {")
    lines.append("  ledId: number;")
    lines.append("  /** Phone monotonic clock at frame capture, in milliseconds. */")
    lines.append("  tCaptureMs: number;")
    lines.append("  /** Sub-pixel centroid x (origin top-left). */")
    lines.append("  u: number;")
    lines.append("  /** Sub-pixel centroid y (origin top-left). */")
    lines.append("  v: number;")
    lines.append("  imgW: number;")
    lines.append("  imgH: number;")
    lines.append("  K: Intrinsics;")
    lines.append("  /** Camera pose, or null on the WebXR-free capture path (the")
    lines.append("   * visual-inertial reconstructor solves poses jointly; the session")
    lines.append("   * must then carry imu_batch samples). */")
    lines.append("  pose: Pose | null;")
    lines.append("  /** Decoder confidence in [0, 1]. */")
    lines.append("  confidence: number;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// CodeParams (§7.6)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export type Encoding = " + " | ".join(f'"{v}"' for v in encoding_values) + ";")
    lines.append("export type SyncPattern = " + " | ".join(f'"{v}"' for v in sync_values) + ";")
    lines.append("export type Fec = " + " | ".join(f'"{v}"' for v in fec_values) + ";\n")
    lines.append("export interface CodeParams {")
    lines.append("  ledCount: number;")
    lines.append("  /** Coded BITS per cycle: ceil(log2(ledCount+1)) data bits + FEC parity bits;")
    lines.append("   * transmitted log2(symbols) at a time. */")
    lines.append("  bits: number;")
    lines.append("  encoding: Encoding;")
    lines.append("  /** Data-symbol alphabet size (log2(symbols) bits per data frame):")
    lines.append("   * 2 = red/blue, 4 = blue/magenta/red/yellow carrying Gray-ordered")
    lines.append("   * bit pairs. Negotiated by the client from measured chroma SNR. */")
    lines.append("  symbols: number;")
    lines.append("  /** Hold time per frame (symbol window), in milliseconds. */")
    lines.append("  bitPeriodMs: number;")
    lines.append("  syncPattern: SyncPattern;")
    lines.append("  /** 2 (sync delimiter) + ceil(bits / log2(symbols)) data frames */")
    lines.append("  cycleFrames: number;")
    lines.append("  /** FEC around the Gray data word ('secded' = extended Hamming, d=4:")
    lines.append("   * correct 1 misread bit, detect-and-reject 2). Absent = 'none'. */")
    lines.append("  fec?: Fec | undefined;")
    lines.append("  /** LED output brightness scale in [0,1]; absent = 1.0. Servoed by the")
    lines.append("   * phone against measured bloom/wash-out (planLedBrightness). */")
    lines.append("  brightness?: number | undefined;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// OutputMap (§7.5)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface LedEntry {")
    lines.append("  id: number;")
    lines.append("  xyz: Vec3;")
    lines.append("  confidence: number;")
    lines.append("  nViews: number;")
    lines.append("  rmsReprojPx: number;")
    lines.append("  parallaxDeg: number;")
    lines.append("}\n")
    lines.append("export interface OutputMapStats {")
    lines.append("  rmsReprojPxGlobal: number;")
    lines.append("  medianParallaxDeg: number;")
    lines.append("}\n")
    lines.append("export interface OutputMap {")
    lines.append("  mapId: string;")
    lines.append("  /** ISO-8601 timestamp. */")
    lines.append("  createdAt: string;")
    units_ts = " | ".join('"' + v + '"' for v in units_values)
    frame_ts = " | ".join('"' + v + '"' for v in frame_values)
    lines.append(f"  units: {units_ts};")
    lines.append(f"  frame: {frame_ts};")
    lines.append("  ledCount: number;")
    lines.append("  leds: LedEntry[];")
    lines.append("  unmapped: number[];")
    lines.append("  /** Solved camera path (decimated, chronological) — present for")
    lines.append("   * visual-inertial solves; same frame as leds. */")
    lines.append("  trajectory?: Vec3[] | undefined;")
    lines.append("  stats: OutputMapStats;")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Topology (§7.7) — skeletonized fixture, uploaded alongside a map")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface BranchPoint {")
    lines.append("  id: number;")
    lines.append("  /** Position in meters, same frame as the OutputMap. */")
    lines.append("  xyz: Vec3;")
    lines.append("}\n")
    lines.append("export interface TopologySegment {")
    lines.append("  id: number;")
    lines.append("  /** Branch-point id at the segment start (arclength 0); -1 = free end. */")
    lines.append("  a: number;")
    lines.append("  /** Branch-point id at the segment end; -1 = free end. */")
    lines.append("  b: number;")
    lines.append("  /** Polyline from a to b; arclength is measured along it from a. */")
    lines.append("  polyline: Vec3[];")
    lines.append("  /** Total polyline arclength, meters. */")
    lines.append("  length: number;")
    lines.append("}\n")
    lines.append("export interface LedAssociation {")
    lines.append("  ledId: number;")
    lines.append("  segmentId: number;")
    lines.append("  /** Arclength of the LED's foot point along the segment, meters from a. */")
    lines.append("  footArclength: number;")
    lines.append("  /** Perpendicular distance LED -> foot point, meters. */")
    lines.append("  dPerp: number;")
    lines.append("}\n")
    lines.append("/** Skeletonized fixture topology (Phase F output): drives the O(N)")
    lines.append(" * pulse illuminate on players. Keyed to the OutputMap it skeletonizes. */")
    lines.append("export interface Topology {")
    lines.append("  mapId: string;")
    lines.append("  branchPoints: BranchPoint[];")
    lines.append("  segments: TopologySegment[];")
    lines.append("  associations: LedAssociation[];")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// PlaybackParams (§7.8) — effect tunables (pulse reference controls)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("/** All fields are optional overlays: unset keeps the player's current or")
    lines.append(" * default value, so a UI can send just the slider that moved. */")
    lines.append("export interface PlaybackParams {")
    lines.append("  /** Global output brightness scale in [0,1]. */")
    lines.append("  intensity?: number | null;")
    lines.append("  /** Soft-falloff radius around a pulse agent, meters ('soft'). */")
    lines.append("  glowRadius?: number | null;")
    lines.append("  /** Concurrent pulse agents traversing the topology. */")
    lines.append("  agentCount?: number | null;")
    lines.append("  /** Agent travel speed along the topology, m/s. */")
    lines.append("  speed?: number | null;")
    lines.append("  /** Palette as 0xRRGGBB ints; empty/omitted keeps the player default. */")
    lines.append("  palette?: number[];")
    lines.append("}\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Client -> Server messages (§7.1)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface HelloMessage {")
    lines.append('  type: "hello";')
    lines.append("  client: string;")
    lines.append("  appVersion: string;")
    lines.append("}\n")
    lines.append("export interface TimeSyncPingMessage {")
    lines.append('  type: "time_sync_ping";')
    lines.append("  /** Phone clock at send, in milliseconds. */")
    lines.append("  t0: number;")
    lines.append("}\n")
    lines.append("/** The client is the configuration authority: it measured the scene, so it")
    lines.append(" * chooses the symbol alphabet and signaling rate; omitted fields fall back")
    lines.append(" * to server defaults. */")
    lines.append("export interface StartMappingOptions {")
    lines.append("  ledCount: number;")
    lines.append(
        "  /** Symbol alphabet size, chosen from measured chroma SNR: good -> 4, marginal -> 2. */"
    )
    lines.append("  symbols?: number;")
    lines.append(
        "  /** Signaling rate: each symbol window should span >= ~3 camera frame intervals. */"
    )
    lines.append("  bitPeriodMs?: number;")
    lines.append("  /** LED output brightness scale in [0,1]; omitted -> server default 1.0. */")
    lines.append("  brightness?: number;")
    lines.append("}\n")
    lines.append("export interface StartMappingMessage {")
    lines.append('  type: "start_mapping";')
    lines.append("  options: StartMappingOptions;")
    lines.append("}\n")
    lines.append("/** Mid-capture renegotiation: overlay these on the active capture's params,")
    lines.append(
        " * restamp the pattern epoch, keep collected detections. Reply: pattern_state. */"
    )
    lines.append("export interface ConfigureOptions {")
    lines.append("  ledCount?: number;")
    lines.append("  symbols?: number;")
    lines.append("  bitPeriodMs?: number;")
    lines.append("  /** LED output brightness scale in [0,1]; omitted -> keep current. */")
    lines.append("  brightness?: number;")
    lines.append("}\n")
    lines.append("export interface ConfigureMessage {")
    lines.append('  type: "configure";')
    lines.append("  options: ConfigureOptions;")
    lines.append("}\n")
    lines.append("export interface StopMappingMessage {")
    lines.append('  type: "stop_mapping";')
    lines.append("  /** Solver placement (client benchmark decision): true/omitted -> the")
    lines.append("   * server reconstructs and replies result_ready; false -> the server only")
    lines.append("   * stops + persists (reply: mapping_stopped) and the client solves")
    lines.append("   * locally, uploading via submit_map. */")
    lines.append("  solveOnHost?: boolean | null;")
    lines.append("}\n")
    lines.append("/** Upload a client-solved OutputMap (phone-side final solve, wasm). The")
    lines.append(" * server persists it as if it had solved it and replies result_ready. */")
    lines.append("export interface SubmitMapMessage {")
    lines.append('  type: "submit_map";')
    lines.append("  map: OutputMap;")
    lines.append("}\n")
    lines.append("export interface DetectionsMessage {")
    lines.append('  type: "detections";')
    lines.append("  batch: DetectionRecord[];")
    lines.append("}\n")
    lines.append("/** One inertial sample, CAMERA frame (+X right, +Y up, -Z look) — the")
    lines.append(" * client applies its device-specific DeviceMotion axis mapping. */")
    lines.append("export interface ImuSample {")
    lines.append("  /** Phone monotonic clock, ms — same domain as tCaptureMs. */")
    lines.append("  t: number;")
    lines.append("  /** Angular rate [x, y, z], rad/s. */")
    lines.append("  gyro: Vec3;")
    lines.append("  /** Specific force (a − g) [x, y, z], m/s². */")
    lines.append("  accel: Vec3;")
    lines.append("}\n")
    lines.append("/** IMU batch for the WebXR-free capture path: dead reckoning between")
    lines.append(" * frames + metric scale + gravity for the joint pose+LED solve. */")
    lines.append("export interface ImuBatchMessage {")
    lines.append('  type: "imu_batch";')
    lines.append("  samples: ImuSample[];")
    lines.append("}\n")
    lines.append("/** Camera/exposure telemetry (§7.1 exposure_report). The web client cannot")
    lines.append(" * read the real 3A/ISP state (WebXR exposes only the camera texture), so these")
    lines.append(
        " * are software estimates; iso/exposureTimeMs are reserved for clients that can. */"
    )
    lines.append("export interface ExposureStats {")
    lines.append("  /** Phone monotonic clock at the end of the measurement window, ms. */")
    lines.append("  tCaptureMs: number;")
    lines.append("  /** Median camera frame interval, ms — the shutter-speed proxy. */")
    lines.append("  frameIntervalMs: number;")
    lines.append("  /** Mean scene luminance [0,1], unthresholded downsampled frame. */")
    lines.append("  meanLuma: number;")
    lines.append("  /** 95th-percentile scene luminance [0,1]. */")
    lines.append("  p95Luma: number;")
    lines.append("  /** Fraction of pixels at/above 0.98 (saturated highlights). */")
    lines.append("  clipFrac: number;")
    lines.append("  /** Median detector blobs per frame at the current threshold. */")
    lines.append("  blobCount: number;")
    lines.append("  /** Detector luminance threshold in effect. */")
    lines.append("  detectorThreshold: number;")
    lines.append("  /** Real sensor ISO from the 3A/ISP, when the platform exposes it. */")
    lines.append("  iso?: number | null;")
    lines.append("  /** Real sensor exposure time (ms), when the platform exposes it. */")
    lines.append("  exposureTimeMs?: number | null;")
    lines.append("  /** WebXR light-estimation primary intensity (max RGB, relative units). */")
    lines.append("  ambientIntensity?: number | null;")
    lines.append("}\n")
    lines.append("export interface ExposureReportMessage {")
    lines.append('  type: "exposure_report";')
    lines.append("  report: ExposureStats;")
    lines.append("}\n")
    lines.append("export interface GetStatusMessage {")
    lines.append('  type: "get_status";')
    lines.append("}\n")
    lines.append(
        "/** Sent by pattern followers (e.g. the virtual LED wall) to poll the pattern clock. */"
    )
    lines.append("export interface GetPatternMessage {")
    lines.append('  type: "get_pattern";')
    lines.append("}\n")
    lines.append("/** Poll the continuous solver for the latest interim reconstruction. */")
    lines.append("export interface GetLiveMapMessage {")
    lines.append('  type: "get_live_map";')
    lines.append("}\n")
    lines.append("/** Poll the FINAL solve's progress while the stop_mapping reply is pending. */")
    lines.append("export interface GetSolveStatusMessage {")
    lines.append('  type: "get_solve_status";')
    lines.append("}\n")
    lines.append("/** A contiguous run of same-color LEDs in a counting pattern. */")
    lines.append("export interface ColorBlock {")
    lines.append("  start: number;")
    lines.append("  count: number;")
    lines.append("  /** Block color [r, g, b] in [0,1]. */")
    lines.append("  rgb: Vec3;")
    lines.append("}\n")
    lines.append("/** LED-counting handshake (§7.9): display a static color-block pattern.")
    lines.append(" * Blocks paint [start, start+count); uncovered LEDs are off; painting past")
    lines.append(" * the physical strip end IS the probe (the phone binary-searches the length")
    lines.append(" * by observing which blocks light). Empty blocks = all off. Reply:")
    lines.append(" * counting_state. */")
    lines.append("export interface SetCountingPatternMessage {")
    lines.append('  type: "set_counting_pattern";')
    lines.append("  blocks: ColorBlock[];")
    lines.append("  /** Player output channel; null/omitted -> 0. */")
    lines.append("  channel?: number | null;")
    lines.append("}\n")
    lines.append("/** Persist the detected strip length for a channel (defaults future")
    lines.append(" * codeParams.ledCount, bounds playback buffers). Reply: led_count_state. */")
    lines.append("export interface SetLedCountMessage {")
    lines.append('  type: "set_led_count";')
    lines.append("  ledCount: number;")
    lines.append("  /** Player output channel; null/omitted -> 0. */")
    lines.append("  channel?: number | null;")
    lines.append("}\n")
    lines.append("/** Upload the skeletonized topology for a stored map (Phase F). The player")
    lines.append(" * persists it next to the map and replies result_ready (mirrors submit_map). */")
    lines.append("export interface SubmitTopologyMessage {")
    lines.append('  type: "submit_topology";')
    lines.append("  topology: Topology;")
    lines.append("}\n")
    lines.append("/** Playback control (§7.8): select the effect and overlay params. 'off' is")
    lines.append(" * universal; other effects are player-capability-dependent (reply: error")
    lines.append(" * code='unsupported_effect' when not shipped). Reply: playback_state. */")
    lines.append("export interface SetPlaybackMessage {")
    lines.append('  type: "set_playback";')
    lines.append("  effect: string;")
    lines.append("  params?: PlaybackParams | null;")
    lines.append("  /** Stored map/topology to play on; null keeps the current selection. */")
    lines.append("  mapId?: string | null;")
    lines.append("}\n")
    lines.append("/** Poll the current playback state. Reply: playback_state. */")
    lines.append("export interface GetPlaybackMessage {")
    lines.append('  type: "get_playback";')
    lines.append("}\n")
    lines.append("export type ClientMessage =")
    lines.append("  | HelloMessage")
    lines.append("  | TimeSyncPingMessage")
    lines.append("  | StartMappingMessage")
    lines.append("  | ConfigureMessage")
    lines.append("  | StopMappingMessage")
    lines.append("  | SubmitMapMessage")
    lines.append("  | DetectionsMessage")
    lines.append("  | ImuBatchMessage")
    lines.append("  | ExposureReportMessage")
    lines.append("  | GetStatusMessage")
    lines.append("  | GetPatternMessage")
    lines.append("  | GetLiveMapMessage")
    lines.append("  | GetSolveStatusMessage")
    lines.append("  | SetCountingPatternMessage")
    lines.append("  | SetLedCountMessage")
    lines.append("  | SubmitTopologyMessage")
    lines.append("  | SetPlaybackMessage")
    lines.append("  | GetPlaybackMessage;\n")

    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Server -> Client messages (§7.2)")
    lines.append("// ---------------------------------------------------------------------------\n")
    lines.append("export interface WelcomeMessage {")
    lines.append('  type: "welcome";')
    lines.append("  sessionId: string;")
    lines.append("  codeParams: CodeParams;")
    lines.append("  /** Host score on the canned solver benchmark (ms), for the client's")
    lines.append("   * solver-placement decision; null while still measuring. */")
    lines.append("  solverBenchMs: number | null;")
    lines.append("}\n")
    lines.append("/** Reply to stop_mapping with solveOnHost=false: capture stopped + log")
    lines.append(" * persisted, no host solve. The counts echo what the server logged. */")
    lines.append("export interface MappingStoppedMessage {")
    lines.append('  type: "mapping_stopped";')
    lines.append("  detections: number;")
    lines.append("  imuSamples: number;")
    lines.append("}\n")
    lines.append("export interface TimeSyncPongMessage {")
    lines.append('  type: "time_sync_pong";')
    lines.append("  /** Echoed phone clock at original send, in milliseconds. */")
    lines.append("  t0: number;")
    lines.append("  /** Server clock at receive of ping, in milliseconds. */")
    lines.append("  t1: number;")
    lines.append("  /** Server clock at send of pong, in milliseconds. */")
    lines.append("  t2: number;")
    lines.append("}\n")
    lines.append("export interface MappingStartedMessage {")
    lines.append('  type: "mapping_started";')
    lines.append("  /** Server-clock time of the start of a known cycle, in milliseconds. */")
    lines.append("  patternClockEpoch: number;")
    lines.append("  codeParams: CodeParams;")
    lines.append("}\n")
    lines.append("export interface StatusMessage {")
    lines.append('  type: "status";')
    lines.append("  identified: number;")
    lines.append("  total: number;")
    lines.append("  lowParallax: number;")
    lines.append("}\n")
    lines.append("/** Reply to get_pattern: the pattern clock a follower should render against. */")
    lines.append("export interface PatternStateMessage {")
    lines.append('  type: "pattern_state";')
    lines.append("  active: boolean;")
    lines.append(
        "  /** Server-clock start of a known cycle (ms); null when no capture is active. */"
    )
    lines.append("  patternClockEpoch: number | null;")
    lines.append("  codeParams: CodeParams;")
    lines.append("}\n")
    lines.append(
        "/** Reply to get_live_map: latest interim reconstruction; null before the first solve or when idle. */"
    )
    lines.append("export interface LiveMapMessage {")
    lines.append('  type: "live_map";')
    lines.append("  active: boolean;")
    lines.append("  map: OutputMap | null;")
    lines.append("}\n")
    lines.append("/** Interim LED position during a running solve (lightweight preview). */")
    lines.append("export interface SolveLed {")
    lines.append("  id: number;")
    lines.append("  xyz: Vec3;")
    lines.append("}\n")
    lines.append("/** Reply to get_solve_status: the final solve's live state. All-null")
    lines.append(" * fields when no solve is running or it reports no progress. */")
    lines.append("export interface SolveStatusMessage {")
    lines.append('  type: "solve_status";')
    lines.append("  running: boolean;")
    lines.append("  /** Estimated optimizer progress [0,1] (eval budget consumed). */")
    lines.append("  progress: number | null;")
    lines.append("  rmsPx: number | null;")
    lines.append("  leds: SolveLed[] | null;")
    lines.append("  /** Decimated solved camera path, same gauge as leds. */")
    lines.append("  trajectory: Vec3[] | null;")
    lines.append("}\n")
    lines.append("export interface ResultReadyMessage {")
    lines.append('  type: "result_ready";')
    lines.append("  mapId: string;")
    lines.append("}\n")
    lines.append("export interface ErrorMessage {")
    lines.append('  type: "error";')
    lines.append("  code: string;")
    lines.append("  message: string;")
    lines.append("}\n")
    lines.append("/** Reply to set_counting_pattern: whether a counting pattern is displayed")
    lines.append(" * and the server-clock time it latched (the phone's read-valid time). */")
    lines.append("export interface CountingStateMessage {")
    lines.append('  type: "counting_state";')
    lines.append("  active: boolean;")
    lines.append("  /** Server-clock time the pattern took effect (ms); null when inactive. */")
    lines.append("  epochMs: number | null;")
    lines.append("}\n")
    lines.append("/** Reply to set_led_count: echo of the persisted per-channel strip length. */")
    lines.append("export interface LedCountStateMessage {")
    lines.append('  type: "led_count_state";')
    lines.append("  ledCount: number;")
    lines.append("  channel: number;")
    lines.append("}\n")
    lines.append("/** Reply to set_playback / get_playback: the effective configuration (the")
    lines.append(" * player echoes what it actually runs, defaults filled into params). */")
    lines.append("export interface PlaybackStateMessage {")
    lines.append('  type: "playback_state";')
    lines.append("  active: boolean;")
    lines.append('  /** The running effect; "off" when inactive. */')
    lines.append("  effect: string;")
    lines.append("  params: PlaybackParams | null;")
    lines.append("  /** The stored map/topology playback runs on; null when none selected. */")
    lines.append("  mapId: string | null;")
    lines.append("}\n")
    lines.append("export type ServerMessage =")
    lines.append("  | WelcomeMessage")
    lines.append("  | TimeSyncPongMessage")
    lines.append("  | MappingStartedMessage")
    lines.append("  | MappingStoppedMessage")
    lines.append("  | StatusMessage")
    lines.append("  | PatternStateMessage")
    lines.append("  | LiveMapMessage")
    lines.append("  | SolveStatusMessage")
    lines.append("  | ResultReadyMessage")
    lines.append("  | ErrorMessage")
    lines.append("  | CountingStateMessage")
    lines.append("  | LedCountStateMessage")
    lines.append("  | PlaybackStateMessage;")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Python (Pydantic v2) emitter
# ---------------------------------------------------------------------------


PY_HEADER = '''"""LED Mapper protocol — Pydantic v2 models (generated).

AUTO-GENERATED by shared/protocol/codegen.py from shared/protocol/schemas/*.json.
Do not edit by hand. Regenerate via:  bazel build //shared/protocol:codegen

Source of truth is the JSON Schema set under shared/protocol/schemas/.
See design doc §7 for the contracts.

All models set `extra='forbid'` so unknown fields fail loudly — the protocol
package exists to surface contract drift, not to paper over it.

This module is imported and re-exported from `ledmapper_protocol/__init__.py`,
which is the public surface for Python consumers.
"""

from __future__ import annotations

from typing import Annotated, List, Literal, Tuple, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel
'''


def _literal(values: Iterable[str]) -> str:
    return "Literal[" + ", ".join(f'"{v}"' for v in values) + "]"


def emit_python(schemas: dict[str, dict]) -> str:
    cp = schemas["code_params"]
    encoding_values = cp["properties"]["encoding"]["enum"]
    sync_values = cp["properties"]["syncPattern"]["enum"]
    fec_values = cp["properties"]["fec"]["enum"]
    omap = schemas["output_map"]
    units_values = omap["properties"]["units"]["enum"]
    frame_values = omap["properties"]["frame"]["enum"]

    out: list[str] = [PY_HEADER]
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Type aliases for the small fixed-arity arrays.")
    out.append("# pydantic v2 enforces these as fixed-length tuples when typed as Tuple[...].")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("Vec3 = Tuple[float, float, float]")
    out.append("Quat = Tuple[float, float, float, float]")
    out.append("Intrinsics = Tuple[float, float, float, float]")
    out.append("")
    out.append("")
    out.append("class _StrictModel(BaseModel):")
    out.append('    """Common base: forbid unknown fields across the whole protocol."""')
    out.append("")
    out.append('    model_config = ConfigDict(extra="forbid")')
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Pose / DetectionRecord (§7.4)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class Pose(_StrictModel):")
    out.append("    p: Vec3")
    out.append("    q: Quat")
    out.append("")
    out.append("")
    out.append("class DetectionRecord(_StrictModel):")
    out.append("    ledId: int = Field(ge=0)")
    out.append("    tCaptureMs: float")
    out.append("    u: float")
    out.append("    v: float")
    out.append("    imgW: int = Field(ge=1)")
    out.append("    imgH: int = Field(ge=1)")
    out.append("    K: Intrinsics")
    out.append("    # None on the WebXR-free capture path: poses are then solved jointly")
    out.append("    # from the session's imu_batch samples (docs/vio-exploration.md).")
    out.append("    pose: Union[Pose, None] = None")
    out.append("    confidence: float = Field(ge=0.0, le=1.0)")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# CodeParams (§7.6)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append(f"Encoding = {_literal(encoding_values)}")
    out.append(f"SyncPattern = {_literal(sync_values)}")
    out.append(f"Fec = {_literal(fec_values)}")
    out.append("")
    out.append("")
    out.append("class CodeParams(_StrictModel):")
    out.append("    ledCount: int = Field(ge=1)")
    out.append("    # Coded BITS per cycle (data + FEC parity), sent log2(symbols) per frame.")
    out.append("    bits: int = Field(ge=1)")
    out.append("    encoding: Encoding")
    out.append("    # Data-symbol alphabet size: 2 (red/blue) or 4 (Gray-ordered bit pairs).")
    out.append("    symbols: Literal[2, 4]")
    out.append("    bitPeriodMs: float = Field(gt=0.0)")
    out.append("    syncPattern: SyncPattern")
    out.append("    cycleFrames: int = Field(ge=3)")
    out.append('    # FEC around the Gray data word; absent on the wire = "none" (legacy).')
    out.append('    fec: Fec = "none"')
    out.append("    # LED output brightness scale; absent on the wire = 1.0. Servoed by the")
    out.append("    # phone against measured bloom/wash-out (planLedBrightness).")
    out.append("    brightness: Union[float, None] = Field(default=None, ge=0.0, le=1.0)")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# OutputMap (§7.5)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class LedEntry(_StrictModel):")
    out.append("    id: int = Field(ge=0)")
    out.append("    xyz: Vec3")
    out.append("    confidence: float = Field(ge=0.0, le=1.0)")
    out.append("    nViews: int = Field(ge=0)")
    out.append("    rmsReprojPx: float = Field(ge=0.0)")
    out.append("    parallaxDeg: float = Field(ge=0.0)")
    out.append("")
    out.append("")
    out.append("class OutputMapStats(_StrictModel):")
    out.append("    rmsReprojPxGlobal: float = Field(ge=0.0)")
    out.append("    medianParallaxDeg: float = Field(ge=0.0)")
    out.append("")
    out.append("")
    out.append("class OutputMap(_StrictModel):")
    out.append("    mapId: str")
    out.append("    createdAt: str")
    out.append(f"    units: {_literal(units_values)}")
    out.append(f"    frame: {_literal(frame_values)}")
    out.append("    ledCount: int = Field(ge=0)")
    out.append("    leds: List[LedEntry]")
    out.append("    unmapped: List[int]")
    out.append("    # Solved camera path (visual-inertial solves), same frame as leds.")
    out.append("    trajectory: Union[List[Vec3], None] = None")
    out.append("    stats: OutputMapStats")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Topology (§7.7) — skeletonized fixture, uploaded alongside a map")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class BranchPoint(_StrictModel):")
    out.append("    id: int = Field(ge=0)")
    out.append("    # Position in meters, same frame as the OutputMap.")
    out.append("    xyz: Vec3")
    out.append("")
    out.append("")
    out.append("class TopologySegment(_StrictModel):")
    out.append("    id: int = Field(ge=0)")
    out.append("    # Endpoint branch-point ids; -1 = free end. Arclength runs from a to b.")
    out.append("    a: int = Field(ge=-1)")
    out.append("    b: int = Field(ge=-1)")
    out.append("    polyline: List[Vec3] = Field(min_length=2)")
    out.append("    # Total polyline arclength, meters.")
    out.append("    length: float = Field(ge=0.0)")
    out.append("")
    out.append("")
    out.append("class LedAssociation(_StrictModel):")
    out.append("    ledId: int = Field(ge=0)")
    out.append("    segmentId: int = Field(ge=0)")
    out.append("    # Arclength of the LED's foot point along the segment, meters from a.")
    out.append("    footArclength: float = Field(ge=0.0)")
    out.append("    # Perpendicular distance LED -> foot point, meters.")
    out.append("    dPerp: float = Field(ge=0.0)")
    out.append("")
    out.append("")
    out.append("class Topology(_StrictModel):")
    out.append('    """Skeletonized fixture topology (Phase F output): drives the O(N)')
    out.append('    pulse illuminate on players. Keyed to the OutputMap it skeletonizes."""')
    out.append("")
    out.append("    mapId: str")
    out.append("    branchPoints: List[BranchPoint]")
    out.append("    segments: List[TopologySegment]")
    out.append("    associations: List[LedAssociation]")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# PlaybackParams (§7.8) — effect tunables (pulse reference controls)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class PlaybackParams(_StrictModel):")
    out.append('    """All fields are optional overlays: unset keeps the player\'s current')
    out.append('    or default value, so a UI can send just the slider that moved."""')
    out.append("")
    out.append("    intensity: Union[float, None] = Field(default=None, ge=0.0, le=1.0)")
    out.append("    glowRadius: Union[float, None] = Field(default=None, gt=0.0)")
    out.append("    agentCount: Union[int, None] = Field(default=None, ge=1)")
    out.append("    speed: Union[float, None] = Field(default=None, gt=0.0)")
    out.append("    # Palette as 0xRRGGBB ints; empty keeps the player default.")
    out.append("    palette: List[int] = Field(default_factory=list)")
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Client -> Server messages (§7.1)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class HelloMessage(_StrictModel):")
    out.append('    type: Literal["hello"]')
    out.append("    client: str")
    out.append("    appVersion: str")
    out.append("")
    out.append("")
    out.append("class TimeSyncPingMessage(_StrictModel):")
    out.append('    type: Literal["time_sync_ping"]')
    out.append("    t0: float")
    out.append("")
    out.append("")
    out.append("class StartMappingOptions(_StrictModel):")
    out.append('    """Client-chosen capture configuration; omitted fields -> server defaults."""')
    out.append("")
    out.append("    ledCount: int = Field(ge=1)")
    out.append("    symbols: Union[Literal[2, 4], None] = None")
    out.append("    bitPeriodMs: Union[float, None] = Field(default=None, gt=0.0)")
    out.append("    brightness: Union[float, None] = Field(default=None, ge=0.0, le=1.0)")
    out.append("")
    out.append("")
    out.append("class StartMappingMessage(_StrictModel):")
    out.append('    type: Literal["start_mapping"]')
    out.append("    options: StartMappingOptions")
    out.append("")
    out.append("")
    out.append("class ConfigureOptions(_StrictModel):")
    out.append(
        '    """Mid-capture renegotiation overlay; unset fields keep their current value."""'
    )
    out.append("")
    out.append("    ledCount: Union[int, None] = Field(default=None, ge=1)")
    out.append("    symbols: Union[Literal[2, 4], None] = None")
    out.append("    bitPeriodMs: Union[float, None] = Field(default=None, gt=0.0)")
    out.append("    brightness: Union[float, None] = Field(default=None, ge=0.0, le=1.0)")
    out.append("")
    out.append("")
    out.append("class ConfigureMessage(_StrictModel):")
    out.append('    type: Literal["configure"]')
    out.append("    options: ConfigureOptions")
    out.append("")
    out.append("")
    out.append("class StopMappingMessage(_StrictModel):")
    out.append('    """solveOnHost (solver placement, from the client\'s init benchmark):')
    out.append("    True/None -> server reconstructs, replies result_ready; False -> stop +")
    out.append('    persist only (reply mapping_stopped), client solves and submit_map\'s."""')
    out.append("")
    out.append('    type: Literal["stop_mapping"]')
    out.append("    solveOnHost: Union[bool, None] = None")
    out.append("")
    out.append("")
    out.append("class SubmitMapMessage(_StrictModel):")
    out.append('    """Client-solved OutputMap upload (phone-side final solve, wasm); the')
    out.append('    server persists it and replies result_ready."""')
    out.append("")
    out.append('    type: Literal["submit_map"]')
    out.append("    map: OutputMap")
    out.append("")
    out.append("")
    out.append("class DetectionsMessage(_StrictModel):")
    out.append('    type: Literal["detections"]')
    out.append("    batch: List[DetectionRecord]")
    out.append("")
    out.append("")
    out.append("class ImuSample(_StrictModel):")
    out.append('    """One inertial sample, CAMERA frame — the client applies its')
    out.append('    device-specific DeviceMotion axis mapping before sending."""')
    out.append("")
    out.append("    t: float")
    out.append("    gyro: Vec3")
    out.append("    accel: Vec3")
    out.append("")
    out.append("")
    out.append("class ImuBatchMessage(_StrictModel):")
    out.append('    type: Literal["imu_batch"]')
    out.append("    samples: List[ImuSample]")
    out.append("")
    out.append("")
    out.append("class ExposureStats(_StrictModel):")
    out.append('    """Camera/exposure telemetry: software estimates from the web client;')
    out.append('    iso/exposureTimeMs are reserved for clients that can read the real 3A."""')
    out.append("")
    out.append("    tCaptureMs: float")
    out.append("    frameIntervalMs: float = Field(gt=0.0)")
    out.append("    meanLuma: float = Field(ge=0.0, le=1.0)")
    out.append("    p95Luma: float = Field(ge=0.0, le=1.0)")
    out.append("    clipFrac: float = Field(ge=0.0, le=1.0)")
    out.append("    blobCount: int = Field(ge=0)")
    out.append("    detectorThreshold: float = Field(ge=0.0, le=1.0)")
    out.append("    iso: Union[float, None] = None")
    out.append("    exposureTimeMs: Union[float, None] = None")
    out.append("    ambientIntensity: Union[float, None] = None")
    out.append("")
    out.append("")
    out.append("class ExposureReportMessage(_StrictModel):")
    out.append('    type: Literal["exposure_report"]')
    out.append("    report: ExposureStats")
    out.append("")
    out.append("")
    out.append("class GetStatusMessage(_StrictModel):")
    out.append('    type: Literal["get_status"]')
    out.append("")
    out.append("")
    out.append("class GetPatternMessage(_StrictModel):")
    out.append(
        '    """Sent by pattern followers (e.g. the virtual LED wall) to poll the pattern clock."""'
    )
    out.append("")
    out.append('    type: Literal["get_pattern"]')
    out.append("")
    out.append("")
    out.append("class GetLiveMapMessage(_StrictModel):")
    out.append('    """Poll the continuous solver for the latest interim reconstruction."""')
    out.append("")
    out.append('    type: Literal["get_live_map"]')
    out.append("")
    out.append("")
    out.append("class GetSolveStatusMessage(_StrictModel):")
    out.append('    """Poll the FINAL solve\'s progress while stop_mapping is pending."""')
    out.append("")
    out.append('    type: Literal["get_solve_status"]')
    out.append("")
    out.append("")
    out.append("class ColorBlock(_StrictModel):")
    out.append('    """A contiguous run of same-color LEDs in a counting pattern."""')
    out.append("")
    out.append("    start: int = Field(ge=0)")
    out.append("    count: int = Field(ge=1)")
    out.append("    # Block color [r, g, b] in [0,1].")
    out.append("    rgb: Vec3")
    out.append("")
    out.append("")
    out.append("class SetCountingPatternMessage(_StrictModel):")
    out.append('    """LED-counting handshake (§7.9): display a static color-block pattern.')
    out.append("    Blocks paint [start, start+count); uncovered LEDs are off; painting past")
    out.append("    the physical strip end IS the probe. Empty blocks = all off. Reply:")
    out.append('    counting_state."""')
    out.append("")
    out.append('    type: Literal["set_counting_pattern"]')
    out.append("    blocks: List[ColorBlock]")
    out.append("    # Player output channel; None -> 0.")
    out.append("    channel: Union[int, None] = Field(default=None, ge=0)")
    out.append("")
    out.append("")
    out.append("class SetLedCountMessage(_StrictModel):")
    out.append('    """Persist the detected strip length for a channel. Reply: led_count_state."""')
    out.append("")
    out.append('    type: Literal["set_led_count"]')
    out.append("    ledCount: int = Field(ge=0)")
    out.append("    channel: Union[int, None] = Field(default=None, ge=0)")
    out.append("")
    out.append("")
    out.append("class SubmitTopologyMessage(_StrictModel):")
    out.append('    """Upload the skeletonized topology for a stored map (Phase F); the')
    out.append('    player persists it next to the map and replies result_ready."""')
    out.append("")
    out.append('    type: Literal["submit_topology"]')
    out.append("    topology: Topology")
    out.append("")
    out.append("")
    out.append("class SetPlaybackMessage(_StrictModel):")
    out.append('    """Playback control (§7.8): select the effect and overlay params. \'off\'')
    out.append("    is universal; other effects are player-capability-dependent (reply: error")
    out.append('    code=\'unsupported_effect\' when not shipped). Reply: playback_state."""')
    out.append("")
    out.append('    type: Literal["set_playback"]')
    out.append("    effect: str")
    out.append("    params: Union[PlaybackParams, None] = None")
    out.append("    # Stored map/topology to play on; None keeps the current selection.")
    out.append("    mapId: Union[str, None] = None")
    out.append("")
    out.append("")
    out.append("class GetPlaybackMessage(_StrictModel):")
    out.append('    """Poll the current playback state. Reply: playback_state."""')
    out.append("")
    out.append('    type: Literal["get_playback"]')
    out.append("")
    out.append("")
    out.append("ClientMessageInner = Annotated[")
    out.append("    Union[")
    out.append("        HelloMessage,")
    out.append("        TimeSyncPingMessage,")
    out.append("        StartMappingMessage,")
    out.append("        ConfigureMessage,")
    out.append("        StopMappingMessage,")
    out.append("        SubmitMapMessage,")
    out.append("        DetectionsMessage,")
    out.append("        ImuBatchMessage,")
    out.append("        ExposureReportMessage,")
    out.append("        GetStatusMessage,")
    out.append("        GetPatternMessage,")
    out.append("        GetLiveMapMessage,")
    out.append("        GetSolveStatusMessage,")
    out.append("        SetCountingPatternMessage,")
    out.append("        SetLedCountMessage,")
    out.append("        SubmitTopologyMessage,")
    out.append("        SetPlaybackMessage,")
    out.append("        GetPlaybackMessage,")
    out.append("    ],")
    out.append('    Field(discriminator="type"),')
    out.append("]")
    out.append("")
    out.append("")
    out.append("class ClientMessage(RootModel[ClientMessageInner]):")
    out.append('    """Discriminated union of all client (phone) -> server (Pi) messages."""')
    out.append("")
    out.append("")
    out.append("# ---------------------------------------------------------------------------")
    out.append("# Server -> Client messages (§7.2)")
    out.append("# ---------------------------------------------------------------------------")
    out.append("")
    out.append("")
    out.append("class WelcomeMessage(_StrictModel):")
    out.append('    """solverBenchMs: host score on the canned solver benchmark (ms), for')
    out.append('    the client\'s solver-placement decision; None while still measuring."""')
    out.append("")
    out.append('    type: Literal["welcome"]')
    out.append("    sessionId: str")
    out.append("    codeParams: CodeParams")
    out.append("    solverBenchMs: Union[float, None] = None")
    out.append("")
    out.append("")
    out.append("class MappingStoppedMessage(_StrictModel):")
    out.append('    """Reply to stop_mapping(solveOnHost=False): stopped + persisted, no')
    out.append('    host solve; counts echo what the server logged."""')
    out.append("")
    out.append('    type: Literal["mapping_stopped"]')
    out.append("    detections: int = Field(ge=0)")
    out.append("    imuSamples: int = Field(ge=0)")
    out.append("")
    out.append("")
    out.append("class TimeSyncPongMessage(_StrictModel):")
    out.append('    type: Literal["time_sync_pong"]')
    out.append("    t0: float")
    out.append("    t1: float")
    out.append("    t2: float")
    out.append("")
    out.append("")
    out.append("class MappingStartedMessage(_StrictModel):")
    out.append('    type: Literal["mapping_started"]')
    out.append("    patternClockEpoch: float")
    out.append("    codeParams: CodeParams")
    out.append("")
    out.append("")
    out.append("class StatusMessage(_StrictModel):")
    out.append('    type: Literal["status"]')
    out.append("    identified: int = Field(ge=0)")
    out.append("    total: int = Field(ge=0)")
    out.append("    lowParallax: int = Field(ge=0)")
    out.append("")
    out.append("")
    out.append("class PatternStateMessage(_StrictModel):")
    out.append(
        '    """Reply to get_pattern: the pattern clock a follower should render against."""'
    )
    out.append("")
    out.append('    type: Literal["pattern_state"]')
    out.append("    active: bool")
    out.append("    patternClockEpoch: Union[float, None] = None")
    out.append("    codeParams: CodeParams")
    out.append("")
    out.append("")
    out.append("class LiveMapMessage(_StrictModel):")
    out.append(
        '    """Reply to get_live_map: latest interim reconstruction; None before the first solve or when idle."""'
    )
    out.append("")
    out.append('    type: Literal["live_map"]')
    out.append("    active: bool")
    out.append("    map: Union[OutputMap, None] = None")
    out.append("")
    out.append("")
    out.append("class SolveLed(_StrictModel):")
    out.append('    """Interim LED position during a running solve (lightweight preview)."""')
    out.append("")
    out.append("    id: int = Field(ge=0)")
    out.append("    xyz: Vec3")
    out.append("")
    out.append("")
    out.append("class SolveStatusMessage(_StrictModel):")
    out.append('    """Reply to get_solve_status: the final solve\'s live state."""')
    out.append("")
    out.append('    type: Literal["solve_status"]')
    out.append("    running: bool")
    out.append("    progress: Union[float, None] = Field(default=None, ge=0.0, le=1.0)")
    out.append("    rmsPx: Union[float, None] = None")
    out.append("    leds: Union[List[SolveLed], None] = None")
    out.append("    trajectory: Union[List[Vec3], None] = None")
    out.append("")
    out.append("")
    out.append("class ResultReadyMessage(_StrictModel):")
    out.append('    type: Literal["result_ready"]')
    out.append("    mapId: str")
    out.append("")
    out.append("")
    out.append("class ErrorMessage(_StrictModel):")
    out.append('    type: Literal["error"]')
    out.append("    code: str")
    out.append("    message: str")
    out.append("")
    out.append("")
    out.append("class CountingStateMessage(_StrictModel):")
    out.append('    """Reply to set_counting_pattern: whether a counting pattern is displayed')
    out.append('    and the server-clock time it latched (the phone\'s read-valid time)."""')
    out.append("")
    out.append('    type: Literal["counting_state"]')
    out.append("    active: bool")
    out.append("    # Server-clock time the pattern took effect (ms); None when inactive.")
    out.append("    epochMs: Union[float, None] = None")
    out.append("")
    out.append("")
    out.append("class LedCountStateMessage(_StrictModel):")
    out.append('    """Reply to set_led_count: echo of the persisted per-channel strip length."""')
    out.append("")
    out.append('    type: Literal["led_count_state"]')
    out.append("    ledCount: int = Field(ge=0)")
    out.append("    channel: int = Field(ge=0)")
    out.append("")
    out.append("")
    out.append("class PlaybackStateMessage(_StrictModel):")
    out.append('    """Reply to set_playback / get_playback: the effective configuration (the')
    out.append('    player echoes what it actually runs, defaults filled into params)."""')
    out.append("")
    out.append('    type: Literal["playback_state"]')
    out.append("    active: bool")
    out.append('    # The running effect; "off" when inactive.')
    out.append("    effect: str")
    out.append("    params: Union[PlaybackParams, None] = None")
    out.append("    # The stored map/topology playback runs on; None when none selected.")
    out.append("    mapId: Union[str, None] = None")
    out.append("")
    out.append("")
    out.append("ServerMessageInner = Annotated[")
    out.append("    Union[")
    out.append("        WelcomeMessage,")
    out.append("        TimeSyncPongMessage,")
    out.append("        MappingStartedMessage,")
    out.append("        MappingStoppedMessage,")
    out.append("        StatusMessage,")
    out.append("        PatternStateMessage,")
    out.append("        LiveMapMessage,")
    out.append("        SolveStatusMessage,")
    out.append("        ResultReadyMessage,")
    out.append("        ErrorMessage,")
    out.append("        CountingStateMessage,")
    out.append("        LedCountStateMessage,")
    out.append("        PlaybackStateMessage,")
    out.append("    ],")
    out.append('    Field(discriminator="type"),')
    out.append("]")
    out.append("")
    out.append("")
    out.append("class ServerMessage(RootModel[ServerMessageInner]):")
    out.append('    """Discriminated union of all server (Pi) -> client (phone) messages."""')
    out.append("")
    out.append("")
    out.append("__all__ = [")
    for name in [
        "Vec3",
        "Quat",
        "Intrinsics",
        "Pose",
        "DetectionRecord",
        "Encoding",
        "SyncPattern",
        "Fec",
        "CodeParams",
        "LedEntry",
        "OutputMapStats",
        "OutputMap",
        "BranchPoint",
        "TopologySegment",
        "LedAssociation",
        "Topology",
        "PlaybackParams",
        "HelloMessage",
        "TimeSyncPingMessage",
        "StartMappingOptions",
        "StartMappingMessage",
        "ConfigureOptions",
        "ConfigureMessage",
        "StopMappingMessage",
        "SubmitMapMessage",
        "DetectionsMessage",
        "ImuSample",
        "ImuBatchMessage",
        "ExposureStats",
        "ExposureReportMessage",
        "GetStatusMessage",
        "GetPatternMessage",
        "GetLiveMapMessage",
        "GetSolveStatusMessage",
        "ColorBlock",
        "SetCountingPatternMessage",
        "SetLedCountMessage",
        "SubmitTopologyMessage",
        "SetPlaybackMessage",
        "GetPlaybackMessage",
        "ClientMessage",
        "WelcomeMessage",
        "TimeSyncPongMessage",
        "MappingStartedMessage",
        "MappingStoppedMessage",
        "StatusMessage",
        "PatternStateMessage",
        "LiveMapMessage",
        "SolveLed",
        "SolveStatusMessage",
        "ResultReadyMessage",
        "ErrorMessage",
        "CountingStateMessage",
        "LedCountStateMessage",
        "PlaybackStateMessage",
        "ServerMessage",
    ]:
        out.append(f'    "{name}",')
    out.append("]")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if generated outputs are stale, instead of writing.",
    )
    parser.add_argument(
        "--schema-dir",
        type=Path,
        default=None,
        help="Directory containing *.json schema files. Default: schemas/ next to this script.",
    )
    parser.add_argument(
        "--ts-out",
        type=Path,
        default=None,
        help="Output path for the generated TypeScript file. Default: ts/generated/index.ts.",
    )
    parser.add_argument(
        "--py-out",
        type=Path,
        default=None,
        help="Output path for the generated Pydantic file. Default: python/ledmapper_protocol/_generated.py.",
    )
    args = parser.parse_args()

    schema_dir = args.schema_dir if args.schema_dir is not None else DEFAULT_SCHEMA_DIR
    ts_out = args.ts_out if args.ts_out is not None else DEFAULT_TS_OUT
    py_out = args.py_out if args.py_out is not None else DEFAULT_PY_OUT

    schemas = load_schemas(schema_dir)
    validate_schemas(schemas)

    ts_text = emit_typescript(schemas)
    py_text = emit_python(schemas)

    targets = [(ts_out, ts_text), (py_out, py_text)]

    if args.check:
        stale: list[Path] = []
        for path, expected in targets:
            actual = path.read_text() if path.exists() else ""
            if actual != expected:
                stale.append(path)
        if stale:
            for p in stale:
                print(f"STALE: {p}", file=sys.stderr)
            print(
                "Run `python3 shared/protocol/codegen.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print("All generated files are up to date.")
        return 0

    for path, text in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        try:
            display = path.relative_to(ROOT.parent.parent)
        except ValueError:
            display = path
        print(f"wrote {display}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
