"""LED Mapper protocol — Pydantic v2 models (generated).

AUTO-GENERATED by shared/protocol/codegen.py from shared/protocol/schemas/*.json.
Do not edit by hand. Regenerate via:  bazel build //shared/protocol:codegen

Source of truth is the JSON Schema set under shared/protocol/schemas/.
See design doc §7 for the contracts.

All models set `extra='forbid'` so unknown fields fail loudly — the protocol
package exists to surface contract drift, not to paper over it.

This module is imported and re-exported from `ledmapper_protocol/__init__.py`,
which is the public surface for Python consumers.
"""

from __future__ import annotations

from typing import Annotated, List, Literal, Tuple, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


# ---------------------------------------------------------------------------
# Type aliases for the small fixed-arity arrays.
# pydantic v2 enforces these as fixed-length tuples when typed as Tuple[...].
# ---------------------------------------------------------------------------

Vec3 = Tuple[float, float, float]
Quat = Tuple[float, float, float, float]
Intrinsics = Tuple[float, float, float, float]


class _StrictModel(BaseModel):
    """Common base: forbid unknown fields across the whole protocol."""

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# Pose / DetectionRecord (§7.4)
# ---------------------------------------------------------------------------


class Pose(_StrictModel):
    p: Vec3
    q: Quat


class DetectionRecord(_StrictModel):
    ledId: int = Field(ge=0)
    tCaptureMs: float
    u: float
    v: float
    imgW: int = Field(ge=1)
    imgH: int = Field(ge=1)
    K: Intrinsics
    pose: Pose
    confidence: float = Field(ge=0.0, le=1.0)


# ---------------------------------------------------------------------------
# CodeParams (§7.6)
# ---------------------------------------------------------------------------


Encoding = Literal["gray", "gray-hue"]
SyncPattern = Literal["on_off"]


class CodeParams(_StrictModel):
    ledCount: int = Field(ge=1)
    bits: int = Field(ge=1)
    encoding: Encoding
    bitPeriodMs: float = Field(gt=0.0)
    syncPattern: SyncPattern
    cycleFrames: int = Field(ge=3)


# ---------------------------------------------------------------------------
# OutputMap (§7.5)
# ---------------------------------------------------------------------------


class LedEntry(_StrictModel):
    id: int = Field(ge=0)
    xyz: Vec3
    confidence: float = Field(ge=0.0, le=1.0)
    nViews: int = Field(ge=0)
    rmsReprojPx: float = Field(ge=0.0)
    parallaxDeg: float = Field(ge=0.0)


class OutputMapStats(_StrictModel):
    rmsReprojPxGlobal: float = Field(ge=0.0)
    medianParallaxDeg: float = Field(ge=0.0)


class OutputMap(_StrictModel):
    mapId: str
    createdAt: str
    units: Literal["meters"]
    frame: Literal["webxr_session_ref"]
    ledCount: int = Field(ge=0)
    leds: List[LedEntry]
    unmapped: List[int]
    stats: OutputMapStats


# ---------------------------------------------------------------------------
# Client -> Server messages (§7.1)
# ---------------------------------------------------------------------------


class HelloMessage(_StrictModel):
    type: Literal["hello"]
    client: str
    appVersion: str


class TimeSyncPingMessage(_StrictModel):
    type: Literal["time_sync_ping"]
    t0: float


class StartMappingOptions(_StrictModel):
    ledCount: int = Field(ge=1)


class StartMappingMessage(_StrictModel):
    type: Literal["start_mapping"]
    options: StartMappingOptions


class StopMappingMessage(_StrictModel):
    type: Literal["stop_mapping"]


class DetectionsMessage(_StrictModel):
    type: Literal["detections"]
    batch: List[DetectionRecord]


class GetStatusMessage(_StrictModel):
    type: Literal["get_status"]


class GetPatternMessage(_StrictModel):
    """Sent by pattern followers (e.g. the virtual LED wall) to poll the pattern clock."""

    type: Literal["get_pattern"]


class GetLiveMapMessage(_StrictModel):
    """Poll the continuous solver for the latest interim reconstruction."""

    type: Literal["get_live_map"]


ClientMessageInner = Annotated[
    Union[
        HelloMessage,
        TimeSyncPingMessage,
        StartMappingMessage,
        StopMappingMessage,
        DetectionsMessage,
        GetStatusMessage,
        GetPatternMessage,
        GetLiveMapMessage,
    ],
    Field(discriminator="type"),
]


class ClientMessage(RootModel[ClientMessageInner]):
    """Discriminated union of all client (phone) -> server (Pi) messages."""


# ---------------------------------------------------------------------------
# Server -> Client messages (§7.2)
# ---------------------------------------------------------------------------


class WelcomeMessage(_StrictModel):
    type: Literal["welcome"]
    sessionId: str
    codeParams: CodeParams


class TimeSyncPongMessage(_StrictModel):
    type: Literal["time_sync_pong"]
    t0: float
    t1: float
    t2: float


class MappingStartedMessage(_StrictModel):
    type: Literal["mapping_started"]
    patternClockEpoch: float
    codeParams: CodeParams


class StatusMessage(_StrictModel):
    type: Literal["status"]
    identified: int = Field(ge=0)
    total: int = Field(ge=0)
    lowParallax: int = Field(ge=0)


class PatternStateMessage(_StrictModel):
    """Reply to get_pattern: the pattern clock a follower should render against."""

    type: Literal["pattern_state"]
    active: bool
    patternClockEpoch: Union[float, None]
    codeParams: CodeParams


class LiveMapMessage(_StrictModel):
    """Reply to get_live_map: latest interim reconstruction; None before the first solve or when idle."""

    type: Literal["live_map"]
    active: bool
    map: Union[OutputMap, None]


class ResultReadyMessage(_StrictModel):
    type: Literal["result_ready"]
    mapId: str


class ErrorMessage(_StrictModel):
    type: Literal["error"]
    code: str
    message: str


ServerMessageInner = Annotated[
    Union[
        WelcomeMessage,
        TimeSyncPongMessage,
        MappingStartedMessage,
        StatusMessage,
        PatternStateMessage,
        LiveMapMessage,
        ResultReadyMessage,
        ErrorMessage,
    ],
    Field(discriminator="type"),
]


class ServerMessage(RootModel[ServerMessageInner]):
    """Discriminated union of all server (Pi) -> client (phone) messages."""


__all__ = [
    "Vec3",
    "Quat",
    "Intrinsics",
    "Pose",
    "DetectionRecord",
    "Encoding",
    "SyncPattern",
    "CodeParams",
    "LedEntry",
    "OutputMapStats",
    "OutputMap",
    "HelloMessage",
    "TimeSyncPingMessage",
    "StartMappingOptions",
    "StartMappingMessage",
    "StopMappingMessage",
    "DetectionsMessage",
    "GetStatusMessage",
    "GetPatternMessage",
    "GetLiveMapMessage",
    "ClientMessage",
    "WelcomeMessage",
    "TimeSyncPongMessage",
    "MappingStartedMessage",
    "StatusMessage",
    "PatternStateMessage",
    "LiveMapMessage",
    "ResultReadyMessage",
    "ErrorMessage",
    "ServerMessage",
]
