// Canvas/interaction smoke regression using the actual captured native state.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const native=JSON.parse(fs.readFileSync(process.argv[2]));
let strokes=0;const ctx=new Proxy({},{get:(_,k)=>()=>{if(k==='stroke')strokes++},set:()=>true});
class El {constructor(){this.checked=true;this.style={};this.clientWidth=700;this.clientHeight=550;this.value='';this.children=[];this.className=''}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}add(x){this.children.push(x)}getContext(){return ctx}getBoundingClientRect(){return {left:0,top:0}}setPointerCapture(){}}
const els={};const document={getElementById:id=>els[id]??=new El(),createElement:()=>new El(),createTextNode:t=>t};let saved=null;
const sandbox={document,window:{devicePixelRatio:1},Option:class{constructor(t,v){this.text=t;this.value=v}},console,setTimeout:()=>{},fetch:async(url,args)=>({ok:true,json:async()=>{if(url==='/api/pin')return {pin_id:'test',state:native};if(url==='/api/snapshot'){saved=JSON.parse(args.body);return {id:'test',url:'/snapshot',path:'test.json'}}return native}})};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('hardware/tools/pnr_live/dist/app.js','utf8'),sandbox);
setImmediate(async()=>{await new Promise(r=>setImmediate(r));assert(strokes>0,'native board was rendered');els.board.onwheel({preventDefault(){},clientX:120,clientY:150,deltaY:-100});assert(vm.runInContext('view.scale',sandbox)>1);await els.rect.onclick();els.board.onpointerdown({pointerId:1,clientX:100,clientY:100});els.board.onpointermove({clientX:180,clientY:180});els.board.onpointerup({});await els.snapshot.onclick();assert(saved);assert.equal(saved.annotations.length,1);assert.equal(saved.annotations[0].lane,'r01/candidate-00');assert(saved.annotations[0].bounds.every(Number.isFinite));assert.equal(saved.pin_id,'test');console.log('PASS native canvas render, zoom, pin, draw rectangle, structured snapshot');});
