/**
 * The diffuse-capture striding schedule (src/code/stride.ts): the invariants the
 * whole approach rests on — per-phase non-overlap spacing, full coverage, and a
 * depth-2 registration star so partial per-phase maps fuse with bounded error.
 */

import assert from "node:assert/strict";
import { test } from "node:test";
import {
  isCoveragePhase,
  litLeds,
  phaseCount,
  strideLit,
  type StrideParams,
} from "../src/code/stride";
import golden from "./golden_stride.json";

const CASES: StrideParams[] = [
  { spacing: 3, anchorDensity: 3 },
  { spacing: 4, anchorDensity: 3 },
  { spacing: 5, anchorDensity: 4 },
  { spacing: 8, anchorDensity: 5 },
];
const LED_COUNT = 300;

/** Min nearest-neighbor index distance among a sorted lit set (∞ if <2 lit). */
function minSpacing(lit: number[]): number {
  let m = Infinity;
  for (let i = 1; i < lit.length; i++) m = Math.min(m, lit[i]! - lit[i - 1]!);
  return m;
}

test("phaseCount is 2S-1 (S coverage + S-1 bridges), 1 when disabled", () => {
  for (const p of CASES) assert.equal(phaseCount(p), 2 * p.spacing - 1);
  assert.equal(phaseCount({ spacing: 1, anchorDensity: 3 }), 1);
  // Disabled ⇒ every LED lit.
  assert.deepEqual(litLeds(5, 0, { spacing: 1, anchorDensity: 3 }), [0, 1, 2, 3, 4]);
});

test("every phase keeps lit spots ≥ S apart (non-overlap on the diffuser)", () => {
  for (const p of CASES) {
    for (let ph = 0; ph < phaseCount(p); ph++) {
      const lit = litLeds(LED_COUNT, ph, p);
      assert.ok(lit.length >= 2, `phase ${ph} lit ${lit.length}`);
      assert.ok(
        minSpacing(lit) >= p.spacing,
        `S=${p.spacing} A=${p.anchorDensity} phase ${ph}: min spacing ${minSpacing(lit)} < ${p.spacing}`,
      );
    }
  }
});

test("coverage phases alone light every LED exactly once (a partition)", () => {
  for (const p of CASES) {
    const seen = new Map<number, number>();
    for (let ph = 0; ph < p.spacing; ph++) {
      assert.ok(isCoveragePhase(ph, p));
      for (const led of litLeds(LED_COUNT, ph, p)) seen.set(led, (seen.get(led) ?? 0) + 1);
    }
    for (let led = 0; led < LED_COUNT; led++) {
      assert.equal(seen.get(led), 1, `led ${led} covered ${seen.get(led)}×`);
    }
  }
});

test("bridges wire a depth-2 registration star through coverage-0", () => {
  // Fusion needs each coverage phase to register into coverage-0's frame in ≤2
  // hops: bridge j shares ≥3 class-0 reps with coverage-0 AND ≥3 class-j reps
  // with coverage-j. That makes coverage-0 the hub of a depth-2 star, so every
  // LED is at most two similarity transforms from the global frame.
  const p: StrideParams = { spacing: 4, anchorDensity: 3 };
  const S = p.spacing;
  const coverage = (o: number) => new Set(litLeds(LED_COUNT, o, p));
  const cov0 = coverage(0);
  for (let j = 1; j < S; j++) {
    const bridge = new Set(litLeds(LED_COUNT, S - 1 + j, p));
    const withHub = [...bridge].filter((x) => cov0.has(x));
    const withLeaf = [...bridge].filter((x) => coverage(j).has(x));
    assert.ok(withHub.length >= 3, `bridge ${j}: only ${withHub.length} reps shared with coverage-0`);
    assert.ok(withLeaf.length >= 3, `bridge ${j}: only ${withLeaf.length} reps shared with coverage-${j}`);
  }
});

test("matches the cross-language golden (pins TS ↔ firmware Rust)", () => {
  // golden_stride.json is generated by shared/protocol/gen_golden_stride.py and
  // ALSO checked by //firmware/pattern:golden_stride_test — one wire for both ends.
  for (const c of golden.cases) {
    const p: StrideParams = { spacing: c.spacing, anchorDensity: c.anchorDensity };
    assert.equal(phaseCount(p), c.phaseCount, `phaseCount S=${c.spacing}`);
    assert.equal(c.phases.length, c.phaseCount);
    for (let ph = 0; ph < c.phaseCount; ph++) {
      assert.deepEqual(litLeds(c.ledCount, ph, p), c.phases[ph], `lit set S=${c.spacing} phase ${ph}`);
    }
  }
});

test("strideLit wraps out-of-range phases (running counter convenience)", () => {
  const p: StrideParams = { spacing: 3, anchorDensity: 3 };
  const n = phaseCount(p);
  for (let led = 0; led < 20; led++) {
    assert.equal(strideLit(led, n + 1, p), strideLit(led, 1, p));
    assert.equal(strideLit(led, -1, p), strideLit(led, n - 1, p));
  }
});
