//! Rust/micropb leg of the cross-language proto conformance test (M10).
//!
//! Reads the SAME golden the TS test verifies (web/tests/golden_proto_frames
//! .json, generated by //pi/server:gen_proto_golden from canonical Python
//! encodings) and requires every frame to decode through the micropb-generated
//! bindings and RE-ENCODE TO THE IDENTICAL BYTES. Byte-parity is the strongest
//! form of the conformance contract: it pins micropb's proto3 presence rules
//! (implicit fields skipped at default, optionals/oneofs encoded when set) and
//! packed-repeated encoding to what canonical protobuf (Python) produces, so a
//! phone <-> firmware wire disagreement cannot hide behind "decodes the same".

use base64::Engine;
use ledmapper_pb::ledmapper_::v1_ as pb;
use micropb::{MessageDecode, MessageEncode, PbEncoder};

/// Comfortably above the largest golden frame; encode errors on overflow.
type FrameBuf = micropb::heapless::Vec<u8, 16384>;

fn roundtrip<M: MessageDecode + MessageEncode + Default>(bytes: &[u8], label: &str) -> M {
    let mut msg = M::default();
    msg.decode_from_bytes(bytes)
        .unwrap_or_else(|e| panic!("{label}: decode failed: {e:?}"));
    let mut enc = PbEncoder::new(FrameBuf::new());
    msg.encode(&mut enc)
        .unwrap_or_else(|e| panic!("{label}: re-encode failed: {e:?}"));
    assert_eq!(
        enc.into_writer().as_slice(),
        bytes,
        "{label}: re-encoded bytes differ from the canonical (Python) encoding"
    );
    msg
}

fn golden_frames() -> Vec<(String, Vec<u8>)> {
    let path = std::env::var("GOLDEN_PROTO_FRAMES").expect("GOLDEN_PROTO_FRAMES not set");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let json: serde_json::Value = serde_json::from_str(&text).expect("golden is valid JSON");
    let b64 = base64::engine::general_purpose::STANDARD;
    json["frames"]
        .as_array()
        .expect("frames array")
        .iter()
        .map(|f| {
            (
                f["direction"].as_str().expect("direction").to_string(),
                b64.decode(f["frameB64"].as_str().expect("frameB64"))
                    .expect("valid base64"),
            )
        })
        .collect()
}

#[test]
fn every_golden_frame_roundtrips_byte_identically() {
    let frames = golden_frames();
    assert!(frames.len() >= 40, "expected the full golden, got {} frames", frames.len());
    let mut client = 0;
    let mut server = 0;
    for (i, (direction, bytes)) in frames.iter().enumerate() {
        let label = format!("frame[{i}] ({direction})");
        match direction.as_str() {
            "client" => {
                let msg: pb::ClientMessage = roundtrip(bytes, &label);
                assert!(msg.r#msg.is_some(), "{label}: envelope has no arm set");
                client += 1;
            }
            "server" => {
                let msg: pb::ServerMessage = roundtrip(bytes, &label);
                assert!(msg.r#msg.is_some(), "{label}: envelope has no arm set");
                server += 1;
            }
            other => panic!("unknown direction {other:?}"),
        }
    }
    assert!(client > 0 && server > 0);
}

/// Spot-check decoded VALUES (not just byte-parity) on one frame per
/// direction, so a systematic field-number/type mixup that happens to
/// re-encode consistently would still be caught.
#[test]
fn decoded_values_match_the_canonical_examples() {
    let frames = golden_frames();

    // The first server frame is welcome{sessionId:"s-1", codeParams:...,
    // solverBenchMs:null} (pi/server/server/proto_examples.py).
    let (_, bytes) = frames.iter().find(|(d, _)| d == "server").expect("server frame");
    let mut msg = pb::ServerMessage::default();
    msg.decode_from_bytes(bytes).unwrap();
    match msg.r#msg.expect("arm") {
        pb::ServerMessage_::Msg::Welcome(w) => {
            assert_eq!(w.r#session_id.as_str(), "s-1");
            assert!(!w._has.r#solver_bench_ms(), "solverBenchMs is null in the example");
            let cp = &w.r#code_params;
            assert_eq!(cp.r#led_count, 64);
            assert_eq!(cp.r#bits, 12);
            assert_eq!(cp.r#symbols, 4);
            assert_eq!(cp.r#encoding.as_str(), "hue");
            assert_eq!(cp.r#fec.as_str(), "secded");
            assert_eq!(cp.r#bit_period_ms, 110.0);
        }
        other => panic!("first server frame should be welcome, got {other:?}"),
    }

    // The set_counting_pattern example: two 64-LED blocks, channel 1.
    let counting = frames
        .iter()
        .filter(|(d, _)| d == "client")
        .find_map(|(_, bytes)| {
            let mut msg = pb::ClientMessage::default();
            msg.decode_from_bytes(bytes).ok()?;
            match msg.r#msg? {
                pb::ClientMessage_::Msg::SetCountingPattern(p) if !p.r#blocks.is_empty() => {
                    Some(p)
                }
                _ => None,
            }
        })
        .expect("a non-empty set_counting_pattern frame");
    assert_eq!(counting.r#blocks.len(), 2);
    assert_eq!(counting.r#blocks[0].r#start, 0);
    assert_eq!(counting.r#blocks[0].r#count, 64);
    assert_eq!(counting.r#blocks[0].r#rgb.as_slice(), &[1.0, 0.0, 0.0]);
    assert_eq!(counting.r#blocks[1].r#start, 64);
    assert_eq!(counting.r#channel(), Some(&1));

    // The submit_topology example: polyline + association survive intact.
    let topo = frames
        .iter()
        .filter(|(d, _)| d == "client")
        .find_map(|(_, bytes)| {
            let mut msg = pb::ClientMessage::default();
            msg.decode_from_bytes(bytes).ok()?;
            match msg.r#msg? {
                pb::ClientMessage_::Msg::SubmitTopology(t) => Some(t),
                _ => None,
            }
        })
        .expect("a submit_topology frame");
    let t = &topo.r#topology;
    assert_eq!(t.r#map_id.as_str(), "m-1");
    assert_eq!(t.r#segments.len(), 1);
    assert_eq!(t.r#segments[0].r#b, -1);
    assert_eq!(t.r#segments[0].r#polyline.len(), 3);
    assert_eq!(t.r#segments[0].r#polyline[0].r#v.as_slice(), &[0.0, 0.1, 0.0]);
    assert_eq!(t.r#associations[0].r#foot_arclength, 0.25);
}
