#!/usr/bin/env python3
"""Generate the PWA / app icons for the Splanc web app from the brand splash mark.

The single source of truth is `brand-splash.svg` (next to this script): the white
"splash" mark on a transparent canvas, with flat transforms. This script measures
the mark's bounding box, centers it, and composites it on the app's dark background
at the sizes each platform needs, emitting BOTH the vector icons (app-icon*.svg) and
the raster PNGs (apple-touch-icon.png + icon-{192,512}.png + icon-maskable-512.png).

Keeping the raster and vector icons in sync is the whole point: an earlier rebrand
updated only the SVGs, so the PNGs — which iOS home screens and Android WebAPKs
actually use — were left showing the old "tree" art.

The mark is kept as plain <g transform> (no nested <svg x/y>) so browsers and the
rasterizer agree pixel-for-pixel. Regeneration needs PyMuPDF (bundles its own
rasterizer — no system cairo). Outputs are committed, so this is NOT a build step:

    python3 -m venv /tmp/venv && . /tmp/venv/bin/activate && pip install pymupdf
    python3 web/tools/gen_icons.py
"""

import os
import re

import pymupdf

# App background (kit/tokens.css). iOS/Android composite over this; corners are
# rounded for the "any" icon and full-bleed square for maskable / apple-touch.
BG = "#0e0e12"
CANVAS = 512  # art coordinate space; rendered down to each target size
CORNER = 112  # rounded-square radius on the 512 canvas (matches the app card radius)

# Art fill fraction (longer side / canvas) per icon: the "any" tile fills more; the
# maskable tile stays inside the ~80% adaptive-icon safe circle; apple-touch sits
# between (iOS rounds it itself).
FRAC_ANY, FRAC_MASKABLE, FRAC_APPLE = 0.60, 0.54, 0.62

HERE = os.path.dirname(os.path.abspath(__file__))
ICONS = os.path.normpath(os.path.join(HERE, "..", "public", "icons"))


def _art_markup():
    """The inner markup of brand-splash.svg (everything inside the root <svg>)."""
    src = open(os.path.join(HERE, "brand-splash.svg")).read()
    return re.search(r"<svg\b[^>]*>(.*)</svg>", src, re.S).group(1).strip()


ART = _art_markup()


def _svg(inner, rounded):
    rect = (
        f'<rect width="{CANVAS}" height="{CANVAS}" '
        + (f'rx="{CORNER}" ' if rounded else "")
        + f'fill="{BG}"/>'
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" '
        f'width="{CANVAS}" height="{CANVAS}">{rect}{inner}</svg>'
    )


def _render(svg, size, alpha):
    doc = pymupdf.open(stream=svg.encode(), filetype="svg")
    page = doc[0]
    zoom = size / page.rect.width
    return page.get_pixmap(matrix=pymupdf.Matrix(zoom, zoom), alpha=alpha)


def _art_bbox():
    """Bounding box (x0, y0, x1, y1) of the mark on the CANVAS, from an alpha render
    of the art alone (no background)."""
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}" '
        f'width="{CANVAS}" height="{CANVAS}">{ART}</svg>'
    )
    pix = _render(svg, CANVAS, True)
    n, w, h, buf = pix.n, pix.width, pix.height, pix.samples
    x0, y0, x1, y1 = w, h, 0, 0
    for y in range(h):
        row = y * pix.stride
        for x in range(w):
            if buf[row + x * n + (n - 1)]:  # non-zero alpha
                x0, y0 = min(x0, x), min(y0, y)
                x1, y1 = max(x1, x + 1), max(y1, y + 1)
    return x0, y0, x1, y1


BBOX = _art_bbox()


def _centered(frac):
    """ART wrapped in a transform that centers the mark and scales its longer side to
    `frac` of the canvas. Renders identically in browsers and the rasterizer."""
    x0, y0, x1, y1 = BBOX
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    scale = frac * CANVAS / max(x1 - x0, y1 - y0)
    tf = (
        f"translate({CANVAS / 2:.1f} {CANVAS / 2:.1f}) "
        f"scale({scale:.5f}) translate({-cx:.3f} {-cy:.3f})"
    )
    return f'<g transform="{tf}">{ART}</g>'


def _write_svg(path, title, body):
    body = body.replace("><rect", ">\n  <rect", 1).replace("/><g", "/>\n  <g", 1)
    body = body.replace("</svg>", "\n</svg>")
    doc = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- {title} Generated by web/tools/gen_icons.py — DO NOT EDIT BY HAND. -->\n"
        f"{body}\n"
    )
    with open(path, "w") as f:
        f.write(doc)
    print(f"wrote {path}")


def _write_png(path, svg, size, alpha):
    _render(svg, size, alpha).save(path)
    print(f"wrote {path} ({size}x{size}, {'alpha' if alpha else 'opaque'})")


def main():
    os.makedirs(ICONS, exist_ok=True)
    any_svg = _svg(_centered(FRAC_ANY), rounded=True)
    mask_svg = _svg(_centered(FRAC_MASKABLE), rounded=False)
    apple_svg = _svg(_centered(FRAC_APPLE), rounded=False)

    # Vector icons (committed; referenced by the manifest + <link rel=icon>).
    _write_svg(os.path.join(ICONS, "app-icon.svg"), "Splanc app icon (rounded square).", any_svg)
    _write_svg(
        os.path.join(ICONS, "app-icon-maskable.svg"),
        "Splanc maskable app icon (full-bleed; art inside the adaptive safe zone).",
        mask_svg,
    )

    # Raster icons. "any" keeps transparent corners (rounded tile); maskable and
    # apple-touch are full-bleed opaque squares.
    _write_png(os.path.join(ICONS, "icon-192.png"), any_svg, 192, alpha=True)
    _write_png(os.path.join(ICONS, "icon-512.png"), any_svg, 512, alpha=True)
    _write_png(os.path.join(ICONS, "icon-maskable-512.png"), mask_svg, 512, alpha=False)
    _write_png(os.path.join(ICONS, "apple-touch-icon.png"), apple_svg, 180, alpha=False)


if __name__ == "__main__":
    main()
