"""Emit the cross-language protobuf wire golden to stdout.

    bazelisk run //pi/server:gen_proto_golden > web/tests/golden_proto_frames.json

For every canonical §7 example (proto_examples.py): the base64 binary frame
Python produced and the flat dict Python decodes it back to. The TS test
(proto.test.ts) must decode each frame to the same flat object and produce a
frame Python can decode — pinning both boundaries to one wire.
"""

from __future__ import annotations

import base64
import json
import sys

from server import proto_wire
from server.proto_examples import CLIENT_FLATS, SERVER_FLATS


def main() -> int:
    entries = []
    for flat in CLIENT_FLATS:
        frame = proto_wire.encode_client(flat)
        entries.append(
            {
                "direction": "client",
                "frameB64": base64.b64encode(frame).decode(),
                "decoded": proto_wire.decode_client(frame),
            }
        )
    for flat in SERVER_FLATS:
        frame = proto_wire.encode_server(flat)
        entries.append(
            {
                "direction": "server",
                "frameB64": base64.b64encode(frame).decode(),
                "decoded": proto_wire.decode_server(frame),
            }
        )
    json.dump(
        {"comment": "Generated by //pi/server:gen_proto_golden", "frames": entries},
        sys.stdout,
        indent=2,
    )
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
