load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "queue",
    srcs = ["queue.go"],
    importpath = "github.com/fughilli/splanc/pi/hitl/internal/queue",
    visibility = ["//pi/hitl:__subpackages__"],
    deps = [
        "//pi/hitl/internal/api",
        "//pi/hitl/internal/runner",
    ],
)

go_test(
    name = "queue_test",
    srcs = ["queue_test.go"],
    embed = [":queue"],
    deps = ["//pi/hitl/internal/api"],
)
