"""Emit the cross-language golden fixtures for the blink code to stdout.

The TS mirrors (web/src/code/gray.ts, fec.ts) are pinned to the Python driver
logic by JSON goldens under web/tests/. Regenerate after any codeword change:

    bazelisk run //pi/led_driver:gen_golden -- secded16 > web/tests/golden_secded16.json

The golden carries, for a 16-LED SEC-DED code-book: the code parameters, the
per-id transmitted codewords, and the full frame plan (per-frame lit id
lists) — everything the TS tests need to assert frame-for-frame agreement.
"""

from __future__ import annotations

import json
import sys

from led_driver.graycode import codeword, data_bits, default_code_params, frame_plan, gray


def golden_secded16() -> dict:
    params = default_code_params(16)
    assert params.fec == "secded"
    plan = frame_plan(params)
    return {
        "comment": (
            "Generated by pi/led_driver gen_golden.py (the M1 driver logic). "
            "tests/fec.test.ts + gray.test.ts assert the TS mirror agrees "
            "frame-for-frame. Codewords are secded_encode(gray(id+1), k): "
            "extended Hamming d=4 around the Gray data word."
        ),
        "ledCount": params.ledCount,
        "dataBits": data_bits(params.ledCount),
        "bits": params.bits,
        "cycleFrames": params.cycleFrames,
        "fec": params.fec,
        "gray": [gray(i) for i in range(params.ledCount)],
        "codewords": [codeword(i, params) for i in range(params.ledCount)],
        "framePlan": [sorted(s) for s in plan],
    }


def main() -> int:
    which = sys.argv[1] if len(sys.argv) > 1 else "secded16"
    if which != "secded16":
        print(f"unknown golden {which!r}", file=sys.stderr)
        return 1
    json.dump(golden_secded16(), sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
