"""Emit the cross-language golden fixtures for the hue code to stdout.

The TS mirrors (web/src/code/gray.ts, fec.ts) are pinned to the Python driver
logic by JSON goldens under web/tests/. Regenerate after any codeword or
palette change:

    bazelisk run //pi/led_driver:gen_golden -- secded16 > web/tests/golden_secded16.json
    bazelisk run //pi/led_driver:gen_golden -- secded16_sym4 > web/tests/golden_secded16_sym4.json

Each golden carries, for a 16-LED SEC-DED code-book at the given symbol
alphabet: the code parameters, the per-id transmitted codewords, the per-id
per-data-frame symbol values, and the full color plan (per frame, one
palette letter per LED) — everything the TS tests need to assert
frame-for-frame agreement.
"""

from __future__ import annotations

import json
import sys

from led_driver.graycode import (
    BLUE,
    GREEN,
    MAGENTA,
    RED,
    SYMBOL_COLORS,
    WHITE,
    YELLOW,
    codeword,
    color_plan,
    data_bits,
    data_frames,
    default_code_params,
    gray,
    symbol_at,
)

_LETTER = {WHITE: "W", GREEN: "G", RED: "R", BLUE: "B", MAGENTA: "M", YELLOW: "Y"}


def golden(symbols: int) -> dict:
    params = default_code_params(16, symbols=symbols)
    assert params.fec == "secded"
    plan = color_plan(params)
    frames = data_frames(params)
    return {
        "comment": (
            "Generated by pi/led_driver gen_golden.py (the M1 driver logic). "
            "tests/fec.test.ts + gray.test.ts assert the TS mirror agrees "
            "frame-for-frame. Codewords are secded_encode(gray(id+1), k): "
            "extended Hamming d=4 around the Gray data word, transmitted "
            "log2(symbols) bits per frame. Palette letters: W white (ALL_ON "
            "reference), G green (ALL_OFF sync), R red, B blue, M magenta, "
            "Y yellow."
        ),
        "ledCount": params.ledCount,
        "dataBits": data_bits(params.ledCount),
        "bits": params.bits,
        "symbols": params.symbols,
        "cycleFrames": params.cycleFrames,
        "fec": params.fec,
        "gray": [gray(i) for i in range(params.ledCount)],
        "codewords": [codeword(i, params) for i in range(params.ledCount)],
        "symbolValues": [
            [symbol_at(i, f, params) for f in range(frames)] for i in range(params.ledCount)
        ],
        "palette": "".join(_LETTER[c] for c in SYMBOL_COLORS[symbols]),
        "colorPlan": ["".join(_LETTER[c] for c in frame) for frame in plan],
    }


def main() -> int:
    which = sys.argv[1] if len(sys.argv) > 1 else "secded16"
    if which == "secded16":
        out = golden(symbols=2)
    elif which == "secded16_sym4":
        out = golden(symbols=4)
    else:
        print(f"unknown golden {which!r}", file=sys.stderr)
        return 1
    json.dump(out, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
