#!/usr/bin/env python3
"""hostdeploy — run repo build/deploy commands on the HOST for the container agent.

The claude-container agent can't run the macOS-side `bazel run …deploy_live` (it
needs the host's builder VM + SSH to the rig). This tiny watcher bridges that: you
start it once on the host, and the agent submits commands through the shared repo
mount (`.hostdeploy/`). Output streams to a log both sides read; completion writes
a status file.

Usage (on the HOST, from the repo root — leave it running):

    python3 tools/hostdeploy.py

Then the container drives it (see tools/hostrun.sh) by writing
`.hostdeploy/request.json`:

    {"id": "<unique>",
     "argv": ["bazel","run","//pi/hitl:hitl_la.deploy_live","--","hitl-rig-2","--keep-builder"],
     "env": {"SBC_HOSTNAME_OVERRIDE": "hitl-rig-la-1"}}

Safety: only commands whose program (argv[0]) is in ALLOWED run, and always in the
repo root. It's a build/deploy driver, not a shell.

Un-wedgeable by design (a single hung command must never strand the watcher):
  * the child's stdin is /dev/null, so a stray interactive program (e.g. an `ssh`
    that opens a shell) gets EOF immediately and exits instead of blocking forever;
  * the heartbeat runs on its own thread, so `.hostdeploy/alive` stays fresh even
    during a long deploy — staleness means the watcher is DEAD, not merely busy
    (`.hostdeploy/running` reports the in-flight command + its age);
  * every command has a wall-clock timeout (req["timeout"], default DEFAULT_TIMEOUT)
    after which its whole process group is killed (rc=124);
  * the container can abort an orphaned command by writing its id to
    `.hostdeploy/cancel` (tools/hostrun.sh does this from its exit trap).
"""
from __future__ import annotations  # `str | None` on macOS's older python3

import json
import os
import pathlib
import shlex
import shutil
import signal
import subprocess
import sys
import threading
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent  # repo root (tools/..)
BOX = ROOT / ".hostdeploy"
ALLOWED = {"bazel", "bazelisk", "nix", "git"}  # argv[0] allowlist
# Wall-clock backstop for a single command. Deploys are minutes; this only fires on
# a genuinely hung child (e.g. a stuck ssh). Override per-request with req["timeout"].
DEFAULT_TIMEOUT = 3600.0
RUNNING = BOX / "running"  # {id,pid,started} while a command is in flight; removed after
CANCEL = BOX / "cancel"  # container writes the in-flight id here to abort it


def log(msg: str) -> None:
    print(f"[hostdeploy] {msg}", flush=True)


def ssh_shim_path() -> str | None:
    """A dir holding an `ssh` shim that ignores the user known_hosts file, to
    prepend to a deploy's PATH. Returns None if the real ssh can't be found.

    The rigs get reflashed, which rotates their SSH host key. The deploy script
    (sbc_deploy.sh) already uses StrictHostKeyChecking=accept-new, but accept-new
    only auto-trusts BRAND-NEW hosts — a host that is KNOWN with an OLD key still
    fails "Host key verification failed" until someone clears ~/.ssh/known_hosts.
    The script hardcodes its ssh opts (and overwrites $NIX_SSHOPTS), so we can't
    fix this from the environment; instead we shadow `ssh` on PATH with a wrapper
    that pins UserKnownHostsFile=/dev/null. This catches BOTH the script's own
    `ssh` calls and `nix copy`'s ssh-ng transport (both resolve ssh via PATH), so
    the deploy tolerates key rotation without any manual known_hosts surgery. The
    rigs are a private, tailnet-only bench, so not persisting host keys is fine.

    EXCEPTION: only relax connections that DON'T already pin a UserKnownHostsFile.
    The deploy's builder path manages host keys deliberately — the probe
    (`builder_probe_ourkey`) connects to builder@localhost with
    `-o UserKnownHostsFile=$kh` precisely to CAPTURE the VM's host key from that
    file, and nix's own remote-build connection pins the captured key the same way.
    If we force /dev/null on those, the captured key is written to /dev/null, the
    builder host-key comes back empty, and the remote build fails ("failed to start
    SSH connection to builder@linux-builder"). The rig connections we DO want to
    relax set StrictHostKeyChecking=accept-new but no UserKnownHostsFile (so they
    fall back to ~/.ssh/known_hosts, where the stale key lives) — exactly the
    connections this shim targets. So: pass anything that already names a
    UserKnownHostsFile straight through, and relax only the rest.
    """
    real = shutil.which("ssh")
    if not real:
        return None
    shimdir = BOX / "sshshim"
    shimdir.mkdir(parents=True, exist_ok=True)
    shim = shimdir / "ssh"
    shim.write_text(
        "#!/bin/sh\n"
        "# generated by tools/hostdeploy.py — ignore known_hosts so rig key\n"
        "# rotation (reflash) doesn't wedge deploys. Edit the generator, not this.\n"
        "# If the caller already pins a UserKnownHostsFile (the builder probe and\n"
        "# nix's remote-build connection do, to capture/verify the VM host key),\n"
        "# leave it alone — only relax connections that fall back to ~/.ssh/known_hosts.\n"
        'for a in "$@"; do\n'
        f'  case "$a" in *UserKnownHostsFile*|*linux-builder*) exec {shlex.quote(real)} "$@" ;; esac\n'
        "done\n"
        f"exec {shlex.quote(real)} "
        "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=accept-new "
        '-o LogLevel=ERROR "$@"\n'
    )
    shim.chmod(0o755)
    return str(shimdir)


def _cancel_requested(rid: str) -> bool:
    """True if the container asked to abort THIS command (id-matched, so a stale
    cancel for a prior id can't kill a fresh run)."""
    try:
        return CANCEL.exists() and CANCEL.read_text().strip() == rid
    except OSError:
        return False


def _kill_tree(proc: subprocess.Popen) -> None:
    """SIGTERM then (after a grace period) SIGKILL the child's whole process group.
    The child is a session/group leader (start_new_session=True), so this reaps its
    descendants too — ssh, nix, bazel — not just the top process."""
    for sig, grace in ((signal.SIGTERM, 10), (signal.SIGKILL, 0)):
        try:
            os.killpg(proc.pid, sig)
        except ProcessLookupError:
            return  # already gone
        except OSError:
            try:
                proc.send_signal(sig)
            except OSError:
                pass
        for _ in range(int(grace * 2)):
            if proc.poll() is not None:
                return
            time.sleep(0.5)


def _supervise(proc: subprocess.Popen, rid: str, timeout: float, lf) -> str:
    """Wait for proc, killing it on wall-clock timeout or a container cancel.
    Returns a reason ('timeout'/'cancelled') or '' on a normal exit."""
    deadline = time.time() + timeout
    while True:
        try:
            proc.wait(timeout=1.0)
            return ""
        except subprocess.TimeoutExpired:
            pass
        reason = (
            "timeout" if time.time() > deadline else ("cancelled" if _cancel_requested(rid) else "")
        )
        if reason:
            lf.write(f"\n[hostdeploy] {reason} — killing process group {proc.pid}\n")
            lf.flush()
            _kill_tree(proc)
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                pass
            return reason


def run(req: dict) -> None:
    rid = str(req.get("id"))
    argv = req.get("argv") or []
    env = {**os.environ, **(req.get("env") or {})}
    # Shadow `ssh` with a known_hosts-ignoring shim so rig key rotation (reflash)
    # doesn't wedge the deploy on a stale host key. See ssh_shim_path.
    shim = ssh_shim_path()
    if shim:
        env["PATH"] = shim + os.pathsep + env.get("PATH", "")
    statusf = BOX / f"{rid}.status"
    logf = BOX / f"{rid}.log"
    if not argv or argv[0] not in ALLOWED:
        statusf.write_text(json.dumps({"rc": -1, "error": f"argv[0] not allowed: {argv[:1]}"}))
        log(f"REJECTED #{rid}: {argv[:1]} not in {sorted(ALLOWED)}")
        return
    try:
        timeout = float(req.get("timeout") or DEFAULT_TIMEOUT)
    except (TypeError, ValueError):
        timeout = DEFAULT_TIMEOUT
    pretty = " ".join(shlex.quote(a) for a in argv)
    log(f"running #{rid}: {pretty}")
    envnote = " ".join(f"{k}={v}" for k, v in (req.get("env") or {}).items())
    reason = ""
    with open(logf, "w") as lf:
        lf.write(f"$ {envnote + ' ' if envnote else ''}{pretty}\n")
        lf.flush()
        # stdin=DEVNULL: a stray interactive child (e.g. an `ssh` that opens a shell)
        # reads EOF and exits instead of blocking the watcher forever.
        # start_new_session: own process group, so a timeout/cancel kill reaps the
        # whole tree (ssh + nix + bazel), not just the parent.
        proc = subprocess.Popen(
            argv,
            cwd=str(ROOT),
            env=env,
            stdin=subprocess.DEVNULL,
            stdout=lf,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        RUNNING.write_text(json.dumps({"id": rid, "pid": proc.pid, "started": time.time()}))
        try:
            reason = _supervise(proc, rid, timeout, lf)
        finally:
            try:
                RUNNING.unlink()
            except OSError:
                pass
    rc = 124 if reason == "timeout" else proc.returncode
    status = {"rc": rc}
    if reason:
        status["reason"] = reason
    statusf.write_text(json.dumps(status))
    log(f"done #{rid} rc={rc}" + (f" ({reason})" if reason else ""))


def _heartbeat(alivef: pathlib.Path, stop: threading.Event) -> None:
    """Refresh the liveness stamp on its own thread so it stays fresh even while a
    command runs — the container's preflight can then tell a DEAD watcher (stale
    stamp) from a merely BUSY one (fresh stamp + a `running` marker)."""
    while not stop.is_set():
        try:
            alivef.write_text(str(time.time()))
        except OSError:
            pass
        stop.wait(1.0)


def main() -> int:
    BOX.mkdir(exist_ok=True)
    reqf = BOX / "request.json"
    # A stale `running`/`cancel` from a previous watcher process is meaningless now.
    for f in (RUNNING, CANCEL):
        try:
            f.unlink()
        except OSError:
            pass
    stop = threading.Event()
    hb = threading.Thread(target=_heartbeat, args=(BOX / "alive", stop), daemon=True)
    hb.start()
    log(f"watching {BOX} (repo {ROOT}); allowlist={sorted(ALLOWED)}. Ctrl-C to stop.")
    seen = None
    try:
        while True:
            try:
                if reqf.exists():
                    req = json.loads(reqf.read_text())
                    rid = req.get("id")
                    if rid != seen:
                        seen = rid
                        # Idempotent across restarts: a request that already ran wrote
                        # its <id>.status, so skip it rather than re-executing the last
                        # request.json every time the watcher restarts.
                        if (BOX / f"{rid}.status").exists():
                            log(f"skip #{rid}: already completed (status exists)")
                        else:
                            run(req)
            except Exception as e:  # keep the watcher alive across a bad request
                log(f"error: {e}")
            time.sleep(1)
    except KeyboardInterrupt:
        log("stopping.")
        return 0
    finally:
        stop.set()


if __name__ == "__main__":
    sys.exit(main())
