#!/usr/bin/env python3
"""hostdeploy — run repo build/deploy commands on the HOST for the container agent.

The claude-container agent can't run the macOS-side `bazel run …deploy_live` (it
needs the host's builder VM + SSH to the rig). This tiny watcher bridges that: you
start it once on the host, and the agent submits commands through the shared repo
mount (`.hostdeploy/`). Output streams to a log both sides read; completion writes
a status file.

Usage (on the HOST, from the repo root — leave it running):

    python3 tools/hostdeploy.py

Then the container drives it (see tools/hostrun.sh) by writing
`.hostdeploy/request.json`:

    {"id": "<unique>",
     "argv": ["bazel","run","//pi/hitl:hitl_la.deploy_live","--","hitl-rig-2","--keep-builder"],
     "env": {"SBC_HOSTNAME_OVERRIDE": "hitl-rig-la-1"}}

Safety: only commands whose program (argv[0]) is in ALLOWED run, and always in the
repo root. It's a build/deploy driver, not a shell.
"""
from __future__ import annotations  # `str | None` on macOS's older python3

import json
import os
import pathlib
import shlex
import shutil
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent  # repo root (tools/..)
BOX = ROOT / ".hostdeploy"
ALLOWED = {"bazel", "bazelisk", "nix", "git"}  # argv[0] allowlist


def log(msg: str) -> None:
    print(f"[hostdeploy] {msg}", flush=True)


def ssh_shim_path() -> str | None:
    """A dir holding an `ssh` shim that ignores the user known_hosts file, to
    prepend to a deploy's PATH. Returns None if the real ssh can't be found.

    The rigs get reflashed, which rotates their SSH host key. The deploy script
    (sbc_deploy.sh) already uses StrictHostKeyChecking=accept-new, but accept-new
    only auto-trusts BRAND-NEW hosts — a host that is KNOWN with an OLD key still
    fails "Host key verification failed" until someone clears ~/.ssh/known_hosts.
    The script hardcodes its ssh opts (and overwrites $NIX_SSHOPTS), so we can't
    fix this from the environment; instead we shadow `ssh` on PATH with a wrapper
    that pins UserKnownHostsFile=/dev/null. This catches BOTH the script's own
    `ssh` calls and `nix copy`'s ssh-ng transport (both resolve ssh via PATH), so
    the deploy tolerates key rotation without any manual known_hosts surgery. The
    rigs are a private, tailnet-only bench, so not persisting host keys is fine.

    EXCEPTION: only relax connections that DON'T already pin a UserKnownHostsFile.
    The deploy's builder path manages host keys deliberately — the probe
    (`builder_probe_ourkey`) connects to builder@localhost with
    `-o UserKnownHostsFile=$kh` precisely to CAPTURE the VM's host key from that
    file, and nix's own remote-build connection pins the captured key the same way.
    If we force /dev/null on those, the captured key is written to /dev/null, the
    builder host-key comes back empty, and the remote build fails ("failed to start
    SSH connection to builder@linux-builder"). The rig connections we DO want to
    relax set StrictHostKeyChecking=accept-new but no UserKnownHostsFile (so they
    fall back to ~/.ssh/known_hosts, where the stale key lives) — exactly the
    connections this shim targets. So: pass anything that already names a
    UserKnownHostsFile straight through, and relax only the rest.
    """
    real = shutil.which("ssh")
    if not real:
        return None
    shimdir = BOX / "sshshim"
    shimdir.mkdir(parents=True, exist_ok=True)
    shim = shimdir / "ssh"
    shim.write_text(
        "#!/bin/sh\n"
        "# generated by tools/hostdeploy.py — ignore known_hosts so rig key\n"
        "# rotation (reflash) doesn't wedge deploys. Edit the generator, not this.\n"
        "# If the caller already pins a UserKnownHostsFile (the builder probe and\n"
        "# nix's remote-build connection do, to capture/verify the VM host key),\n"
        "# leave it alone — only relax connections that fall back to ~/.ssh/known_hosts.\n"
        'for a in "$@"; do\n'
        f'  case "$a" in *UserKnownHostsFile*|*linux-builder*) exec {shlex.quote(real)} "$@" ;; esac\n'
        "done\n"
        f"exec {shlex.quote(real)} "
        "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=accept-new "
        '-o LogLevel=ERROR "$@"\n'
    )
    shim.chmod(0o755)
    return str(shimdir)


def run(req: dict) -> None:
    rid = str(req.get("id"))
    argv = req.get("argv") or []
    env = {**os.environ, **(req.get("env") or {})}
    # Shadow `ssh` with a known_hosts-ignoring shim so rig key rotation (reflash)
    # doesn't wedge the deploy on a stale host key. See ssh_shim_path.
    shim = ssh_shim_path()
    if shim:
        env["PATH"] = shim + os.pathsep + env.get("PATH", "")
    statusf = BOX / f"{rid}.status"
    logf = BOX / f"{rid}.log"
    if not argv or argv[0] not in ALLOWED:
        statusf.write_text(json.dumps({"rc": -1, "error": f"argv[0] not allowed: {argv[:1]}"}))
        log(f"REJECTED #{rid}: {argv[:1]} not in {sorted(ALLOWED)}")
        return
    pretty = " ".join(shlex.quote(a) for a in argv)
    log(f"running #{rid}: {pretty}")
    envnote = " ".join(f"{k}={v}" for k, v in (req.get("env") or {}).items())
    with open(logf, "w") as lf:
        lf.write(f"$ {envnote + ' ' if envnote else ''}{pretty}\n")
        lf.flush()
        rc = subprocess.call(argv, cwd=str(ROOT), env=env, stdout=lf, stderr=subprocess.STDOUT)
    statusf.write_text(json.dumps({"rc": rc}))
    log(f"done #{rid} rc={rc}")


def main() -> int:
    BOX.mkdir(exist_ok=True)
    reqf = BOX / "request.json"
    alivef = BOX / "alive"
    log(f"watching {BOX} (repo {ROOT}); allowlist={sorted(ALLOWED)}. Ctrl-C to stop.")
    seen = None
    while True:
        try:
            alivef.write_text(str(time.time()))
            if reqf.exists():
                req = json.loads(reqf.read_text())
                if req.get("id") != seen:
                    seen = req.get("id")
                    run(req)
        except KeyboardInterrupt:
            log("stopping.")
            return 0
        except Exception as e:  # keep the watcher alive across a bad request
            log(f"error: {e}")
        time.sleep(1)


if __name__ == "__main__":
    sys.exit(main())
