//! Firmware pattern generator vs the phone client's golden fixtures.
//!
//! `web/tests/golden_secded16{,_sym4}.json` are generated by the Python
//! authority (pi/led_driver gen_golden.py) and ALSO verified frame-for-frame
//! by the phone's decoder tests (web/tests/gray.test.ts, fec.test.ts). Making
//! the firmware generator match the same fixtures pins all three
//! implementations to one wire: what the ESP32 will emit is exactly what the
//! phone's CV pipeline is tested to decode.

use ledmapper_pattern as pat;

fn golden(path_env: &str) -> serde_json::Value {
    let path = std::env::var(path_env).unwrap_or_else(|_| panic!("{path_env} not set"));
    serde_json::from_str(&std::fs::read_to_string(&path).expect("read golden"))
        .expect("golden is valid JSON")
}

fn letter(color: pat::Rgb) -> char {
    match color {
        pat::WHITE => 'W',
        pat::GREEN => 'G',
        pat::RED => 'R',
        pat::BLUE => 'B',
        pat::MAGENTA => 'M',
        pat::YELLOW => 'Y',
        other => panic!("color {other:?} is not in the palette"),
    }
}

fn check_against_golden(g: &serde_json::Value) {
    let led_count = g["ledCount"].as_u64().unwrap() as u32;
    let symbols = g["symbols"].as_u64().unwrap() as u8;
    let secded = g["fec"].as_str().unwrap() == "secded";

    // The code-book derivation reproduces the golden's header.
    let spec = pat::CodeSpec::derive(led_count, symbols, secded);
    assert_eq!(pat::data_bits(led_count) as u64, g["dataBits"].as_u64().unwrap());
    assert_eq!(spec.bits as u64, g["bits"].as_u64().unwrap());
    assert_eq!(spec.cycle_frames as u64, g["cycleFrames"].as_u64().unwrap());

    // Gray table.
    for (i, v) in g["gray"].as_array().unwrap().iter().enumerate() {
        assert_eq!(pat::gray(i as u32) as u64, v.as_u64().unwrap(), "gray({i})");
        assert_eq!(pat::decode_gray(pat::gray(i as u32)), i as u32);
    }

    // Codewords (SEC-DED around gray(id+1)).
    for (id, v) in g["codewords"].as_array().unwrap().iter().enumerate() {
        assert_eq!(
            pat::codeword(id as u32, &spec) as u64,
            v.as_u64().unwrap(),
            "codeword for LED {id}"
        );
    }

    // Per-frame symbol values.
    for (id, frames) in g["symbolValues"].as_array().unwrap().iter().enumerate() {
        for (f, v) in frames.as_array().unwrap().iter().enumerate() {
            assert_eq!(
                pat::symbol_at(id as u32, f as u32, &spec) as u64,
                v.as_u64().unwrap(),
                "symbol for LED {id} data frame {f}"
            );
        }
    }

    // The full color plan, letter for letter.
    let plan = g["colorPlan"].as_array().unwrap();
    assert_eq!(plan.len() as u32, spec.cycle_frames);
    for (f, row) in plan.iter().enumerate() {
        let row = row.as_str().unwrap();
        assert_eq!(row.len() as u32, led_count);
        for (id, expected) in row.chars().enumerate() {
            let got = letter(pat::color_for_frame(id as u32, f as u32, &spec));
            assert_eq!(got, expected, "frame {f}, LED {id}");
        }
    }
}

#[test]
fn matches_the_two_symbol_golden() {
    check_against_golden(&golden("GOLDEN_SECDED16"));
}

#[test]
fn matches_the_four_symbol_golden() {
    check_against_golden(&golden("GOLDEN_SECDED16_SYM4"));
}

#[test]
fn secded_corrects_single_and_rejects_double_errors() {
    let k = pat::data_bits(16); // 5 data bits, the golden's geometry
    let total = pat::secded_total_bits(k);
    for id in 0..16u32 {
        let word = pat::secded_encode(pat::gray(id + 1), k);
        // Clean word decodes uncorrected.
        assert_eq!(pat::secded_decode(word, k), (Some(pat::gray(id + 1)), false));
        // Every single-bit flip is corrected back.
        for b in 0..total {
            let (data, corrected) = pat::secded_decode(word ^ (1 << b), k);
            assert_eq!(data, Some(pat::gray(id + 1)), "flip bit {b} of LED {id}");
            assert!(corrected);
        }
        // Every double flip is detected, never miscorrected.
        for b1 in 0..total {
            for b2 in (b1 + 1)..total {
                let (data, _) = pat::secded_decode(word ^ (1 << b1) ^ (1 << b2), k);
                assert_eq!(data, None, "double flip {b1},{b2} of LED {id}");
            }
        }
    }
}
