//! Firmware stride schedule vs the cross-language golden.
//!
//! `web/tests/golden_stride.json` (generated by shared/protocol/gen_golden_stride.py)
//! is the authority the phone's stride module (web/src/code/stride.ts) is ALSO
//! pinned to — so a firmware/phone divergence in WHICH LEDs light per phase is a
//! test failure here, not a field debugging session on a diffused fixture.

use ledmapper_pattern as pat;

fn golden() -> serde_json::Value {
    let path = std::env::var("GOLDEN_STRIDE").expect("GOLDEN_STRIDE not set");
    serde_json::from_str(&std::fs::read_to_string(&path).expect("read golden"))
        .expect("golden is valid JSON")
}

#[test]
fn matches_the_stride_golden() {
    let g = golden();
    for case in g["cases"].as_array().unwrap() {
        let led_count = case["ledCount"].as_u64().unwrap() as u32;
        let spacing = case["spacing"].as_u64().unwrap() as u32;
        let anchor = case["anchorDensity"].as_u64().unwrap() as u32;
        let phase_count = case["phaseCount"].as_u64().unwrap() as u32;
        assert_eq!(pat::stride_phase_count(spacing), phase_count, "phaseCount for S={spacing}");

        let phases = case["phases"].as_array().unwrap();
        assert_eq!(phases.len() as u32, phase_count);
        for (ph, expected) in phases.iter().enumerate() {
            let expected: Vec<u32> =
                expected.as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as u32).collect();
            let got: Vec<u32> =
                (0..led_count).filter(|&led| pat::stride_lit(led, ph as u32, spacing, anchor)).collect();
            assert_eq!(got, expected, "lit set for S={spacing} A={anchor} phase {ph}");
        }
    }
}

#[test]
fn coverage_phases_partition_and_bridges_are_sparse() {
    // Every LED is lit exactly once across the coverage phases (0..spacing), and
    // every phase keeps its lit spots at least `spacing` apart.
    for (spacing, anchor, n) in [(3u32, 3u32, 40u32), (5, 4, 60)] {
        let mut cover = vec![0u32; n as usize];
        for ph in 0..pat::stride_phase_count(spacing) {
            let lit: Vec<u32> = (0..n).filter(|&led| pat::stride_lit(led, ph, spacing, anchor)).collect();
            for w in lit.windows(2) {
                assert!(w[1] - w[0] >= spacing, "S={spacing} phase {ph}: spacing {} < {spacing}", w[1] - w[0]);
            }
            if pat::stride_is_coverage(ph, spacing) {
                for &led in &lit {
                    cover[led as usize] += 1;
                }
            }
        }
        for (led, &c) in cover.iter().enumerate() {
            assert_eq!(c, 1, "S={spacing}: led {led} covered {c}× by coverage phases");
        }
    }
}

#[test]
fn disabled_when_spacing_is_one() {
    assert_eq!(pat::stride_phase_count(1), 1);
    for led in 0..10 {
        assert!(pat::stride_lit(led, 0, 1, 3));
    }
}
