load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "runner",
    srcs = [
        "podman.go",
        "runner.go",
    ],
    importpath = "github.com/fughilli/splanc/pi/hitl/internal/runner",
    visibility = ["//pi/hitl:__subpackages__"],
    deps = ["//pi/hitl/internal/api"],
)

go_test(
    name = "runner_test",
    srcs = ["podman_test.go"],
    embed = [":runner"],
)
