#!/usr/bin/env bash
#
# Apply Splanc's hand-maintained iOS native config to the Capacitor-generated
# project (docs/design/ios-support.md §4). The `ios/` tree is regenerated by
# `cap add ios` and NOT committed, so this script is the source of truth for the
# native bits we edit — it runs (idempotently) after `cap add ios`, driven by the
# `ios-config` build task in tools/ios_build_server.py.
#
# Runs on the macOS host (uses /usr/libexec/PlistBuddy). Safe to re-run.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
plist="${here}/../ios/App/App/Info.plist"
appdelegate="${here}/../ios/App/App/AppDelegate.swift"
pb=/usr/libexec/PlistBuddy

[ -f "$plist" ] || { echo "no Info.plist at $plist — run 'cap add ios' first" >&2; exit 1; }
[ -x "$pb" ]    || { echo "PlistBuddy not found — this must run on macOS" >&2; exit 1; }

# --- Disable the system "Shake to Undo" gesture. iOS binds a device shake to the
# Undo/Redo alert, which hijacks Acid Mode's own shake-to-enter gesture
# (web/src/ui/acid/shake.ts). Setting applicationSupportsShakeToEdit = false in
# didFinishLaunchingWithOptions turns the system gesture off app-wide, leaving our
# devicemotion handler as the sole responder. The ios/ tree is regenerated, so we
# patch the fresh AppDelegate here (idempotently) rather than committing it.
if [ -f "$appdelegate" ]; then
  if grep -q applicationSupportsShakeToEdit "$appdelegate"; then
    echo "AppDelegate: shake-to-undo already disabled"
  else
    perl -0pi -e 's/(func application\(_ application: UIApplication, didFinishLaunchingWithOptions[^\n]*\{\n)/$1        application.applicationSupportsShakeToEdit = false  \/\/ Splanc: keep Acid Mode shake gesture from triggering system Undo\n/' "$appdelegate"
    if grep -q applicationSupportsShakeToEdit "$appdelegate"; then
      echo "AppDelegate: disabled shake-to-undo"
    else
      echo "WARNING: could not patch $appdelegate — didFinishLaunchingWithOptions signature not found; shake-to-undo left enabled" >&2
    fi
  fi
fi

# --- App icon: overwrite Capacitor's default with the Splanc logo (same as the
# PWA). The asset catalog uses one universal 1024×1024 image (AppIcon-512@2x.png,
# per Contents.json); iOS applies its own rounded-corner mask, so AppIcon-1024.png
# is a full square (no baked rounding). Regenerate it from the SVG with:
#   npx @resvg/resvg-js ... (see web/ios-config/README.md).
appicon_dst="${here}/../ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png"
if [ -d "$(dirname "$appicon_dst")" ]; then
  cp "${here}/AppIcon-1024.png" "$appicon_dst"
  echo "app icon → $appicon_dst"
fi

# Set (or overwrite) a string key. PlistBuddy has no upsert, so try Set then Add.
set_str() {
  local key="$1" val="$2"
  "$pb" -c "Set :$key $val" "$plist" 2>/dev/null || "$pb" -c "Add :$key string $val" "$plist"
}

echo "patching $plist"

# --- Permission usage strings (App Store review REQUIRES these to be present
# and specific; a generic string is a common rejection reason). ----------------
# Camera: the mapping capture pipeline (getUserMedia → WebGL2 detector → solver).
set_str NSCameraUsageDescription \
  "Splanc uses the camera to see your LEDs light up and build a 3D map of your fixture."
# Motion: DeviceMotion/IMU fuses with the camera during mapping (xr/imu.ts).
set_str NSMotionUsageDescription \
  "Splanc reads device motion to steady the camera pose while it maps your LEDs."
# Bluetooth: native Improv provisioning to send Wi-Fi credentials to the device
# (net/capacitorImprov.ts — restores what iOS Safari can't do).
set_str NSBluetoothAlwaysUsageDescription \
  "Splanc uses Bluetooth to hand your Wi-Fi details to a new Splanc device so it can join your network."
set_str NSBluetoothPeripheralUsageDescription \
  "Splanc uses Bluetooth to set up a new Splanc device."
# Local network: reaching the device's wss:// control plane on the LAN (iOS 14+
# gates all local-network traffic behind this prompt).
set_str NSLocalNetworkUsageDescription \
  "Splanc talks to your Splanc device directly on your local network to map fixtures and drive effects."

echo "ios-config applied."
