#!/usr/bin/env bash
#
# Apply Splanc's hand-maintained iOS native config to the Capacitor-generated
# project (docs/design/ios-support.md §4). The `ios/` tree is regenerated by
# `cap add ios` and NOT committed, so this script is the source of truth for the
# native bits we edit — it runs (idempotently) after `cap add ios`, driven by the
# `ios-config` build task in tools/ios_build_server.py.
#
# Runs on the macOS host (uses /usr/libexec/PlistBuddy). Safe to re-run.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
plist="${here}/../ios/App/App/Info.plist"
pb=/usr/libexec/PlistBuddy

[ -f "$plist" ] || { echo "no Info.plist at $plist — run 'cap add ios' first" >&2; exit 1; }
[ -x "$pb" ]    || { echo "PlistBuddy not found — this must run on macOS" >&2; exit 1; }

# Set (or overwrite) a string key. PlistBuddy has no upsert, so try Set then Add.
set_str() {
  local key="$1" val="$2"
  "$pb" -c "Set :$key $val" "$plist" 2>/dev/null || "$pb" -c "Add :$key string $val" "$plist"
}

echo "patching $plist"

# --- Permission usage strings (App Store review REQUIRES these to be present
# and specific; a generic string is a common rejection reason). ----------------
# Camera: the mapping capture pipeline (getUserMedia → WebGL2 detector → solver).
set_str NSCameraUsageDescription \
  "Splanc uses the camera to see your LEDs light up and build a 3D map of your fixture."
# Motion: DeviceMotion/IMU fuses with the camera during mapping (xr/imu.ts).
set_str NSMotionUsageDescription \
  "Splanc reads device motion to steady the camera pose while it maps your LEDs."
# Bluetooth: native Improv provisioning to send Wi-Fi credentials to the device
# (net/capacitorImprov.ts — restores what iOS Safari can't do).
set_str NSBluetoothAlwaysUsageDescription \
  "Splanc uses Bluetooth to hand your Wi-Fi details to a new Splanc device so it can join your network."
set_str NSBluetoothPeripheralUsageDescription \
  "Splanc uses Bluetooth to set up a new Splanc device."
# Local network: reaching the device's wss:// control plane on the LAN (iOS 14+
# gates all local-network traffic behind this prompt).
set_str NSLocalNetworkUsageDescription \
  "Splanc talks to your Splanc device directly on your local network to map fixtures and drive effects."

echo "ios-config applied."
