/**
 * Auto-generate the Splanc user guide (FUG-103) from the shared guide catalog,
 * and gate it in CI so the docs can't silently drift from the app.
 *
 * It reads {@link GUIDE_TOPICS} (`web/src/ui/guide/catalog.ts`) — the SAME data
 * the in-app interactive tutorial is built from — and emits two artifacts:
 *
 *   - `docs/user-guide.md`         a GitHub-rendered Markdown guide (canonical).
 *   - `docs/user-guide/index.html` a self-contained static site (deployed at
 *                                  `/user-guide/`; see web/stage_site.lib.sh),
 *                                  with a real app screenshot (Playwright) per topic,
 *                                  or a schematic figure where one can't be captured.
 *
 * Because both come from the one catalog, the tutorial and the website stay in
 * lockstep: document a feature once (in the catalog) and it appears in both.
 * A new/changed catalog entry that isn't re-pinned fails the freshness gate
 * (`--check` mode + //web:user_guide_freshness), mirroring FUG-95's perf doc.
 *
 * Modeled on the `//web:gen_fx_vm_perf_doc` node CLI. Determinism is the top
 * requirement: no timestamps / absolute paths, stable ordering, and Markdown
 * that is a fixed point of prettier + markdownlint (prose + bullets wrapped to
 * <=100 columns), so regeneration is byte-stable.
 *
 *   # regenerate the checked-in docs in place:
 *   bazel run //web:gen_user_guide
 *
 *   # CI freshness gate (fails if the checked-in docs are stale):
 *   <gen> --check --md-out docs/user-guide.md --html-out docs/user-guide/index.html
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
  GUIDE_TOPICS,
  GUIDE_TAB_LABELS,
  GUIDE_TAB_ORDER,
  type GuideSection,
  type GuideTab,
  type GuideTopic,
} from "../../src/ui/guide/catalog";

const MD_REL_PATH = "docs/user-guide.md";
const HTML_REL_PATH = "docs/user-guide/index.html";
const REGEN_CMD = "bazel run //web:gen_user_guide";
const SHOTS_REL_PATH = "docs/user-guide/shots.json";

/** Where captured screenshots live and how each guide references them. The
 * HTML site (`docs/user-guide/index.html`) sits beside the `img/` subdir; the
 * Markdown (`docs/user-guide.md`, one level up) prefixes `user-guide/`. */
const IMG_DIR = "img";
const MD_IMG_DIR = "user-guide/img";

// -- shared helpers ----------------------------------------------------------

/** Group topics by tab in the canonical GUIDE_TAB_ORDER, preserving in-tab
 * catalog order. Tabs with no topics are skipped. */
function groupByTab(): { tab: GuideTab; topics: GuideTopic[] }[] {
  return GUIDE_TAB_ORDER.map((tab) => ({
    tab,
    topics: GUIDE_TOPICS.filter((t) => t.tab === tab),
  })).filter((g) => g.topics.length > 0);
}

/**
 * Greedy word-wrap to <=`width` columns. Never splits a word, so a URL longer
 * than the width overflows on its own line (markdownlint MD013 allows the
 * generated file's few such cases via code_blocks/tables exemptions; our prose
 * has none). `prefix` is prepended to the first line and `hang` to every
 * continuation — used to wrap bullets under their marker.
 */
function wrap(text: string, width: number, prefix = "", hang = ""): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = prefix;
  let curPrefixLen = prefix.length;
  for (const w of words) {
    const sep = cur.length > curPrefixLen ? " " : "";
    if (cur.length + sep.length + w.length > width && cur.length > curPrefixLen) {
      lines.push(cur);
      cur = hang + w;
      curPrefixLen = hang.length;
    } else {
      cur += sep + w;
    }
  }
  if (cur.length > 0) lines.push(cur);
  return lines;
}

/** GitHub-Flavored-Markdown heading slug (what markdownlint MD051 validates
 * against): lowercase, drop everything but word chars / spaces / hyphens, then
 * spaces to hyphens. Used for the Markdown TOC fragments so they resolve to the
 * auto-generated heading anchors. */
function ghSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s/g, "-");
}

// -- Markdown ----------------------------------------------------------------

function renderMarkdownSection(sec: GuideSection): string[] {
  const out: string[] = [];
  if (sec.heading) {
    out.push(`### ${sec.heading}`);
    out.push("");
  }
  for (const p of sec.body ?? []) {
    out.push(...wrap(p, 100));
    out.push("");
  }
  for (const b of sec.bullets ?? []) {
    out.push(...wrap(b, 100, "- ", "  "));
  }
  if ((sec.bullets ?? []).length > 0) out.push("");
  return out;
}

function renderMarkdown(): string {
  const groups = groupByTab();
  const doc: string[] = [];
  doc.push("<!-- Generated by web/tests/tools/genUserGuide.ts. DO NOT EDIT BY HAND. -->");
  doc.push("");
  doc.push("# Splanc user guide");
  doc.push("");
  doc.push(
    ...wrap(
      "This guide walks through every user-facing feature of Splanc — the phone app for " +
        "mapping, controlling, and animating addressable LED fixtures. It is **auto-generated** " +
        "from the same catalog that drives the app's in-app interactive tutorial " +
        "(`web/src/ui/guide/catalog.ts`), so the two never drift. Regenerate it with:",
      100,
    ),
  );
  doc.push("");
  doc.push("```sh");
  doc.push(REGEN_CMD);
  doc.push("```");
  doc.push("");
  doc.push(
    ...wrap(
      "You can take the same tour interactively inside the app: on first launch a hint offers " +
        "it, and you can restart it any time from **Settings ▸ Help & tutorial**. This document " +
        "is also published as a static site at `/user-guide/` on the deployed app.",
      100,
    ),
  );
  doc.push("");

  // Table of contents.
  doc.push("## Contents");
  doc.push("");
  for (const g of groups) {
    doc.push(`- **${GUIDE_TAB_LABELS[g.tab]}**`);
    for (const t of g.topics) {
      doc.push(...wrap(`[${t.title}](#${ghSlug(t.title)}) — ${t.summary}`, 100, "  - ", "    "));
    }
  }
  doc.push("");

  // Sections.
  for (const g of groups) {
    doc.push(`## ${GUIDE_TAB_LABELS[g.tab]}`);
    doc.push("");
    for (const t of g.topics) {
      doc.push(`### ${t.title}`);
      doc.push("");
      doc.push(`_${t.summary}_`);
      doc.push("");
      // A real captured app screenshot for topics that have one. Byte-varying
      // PNGs aren't freshness-gated; only the stable reference to them is.
      if (t.screenshot) {
        doc.push(`![${t.title} — Splanc app screen](${MD_IMG_DIR}/${t.id}.png)`);
        doc.push("");
      }
      for (const sec of t.sections) {
        // Nudge the section sub-headings one level deeper than the topic (####).
        const rendered = renderMarkdownSection(sec).map((l) =>
          l.startsWith("### ") ? `#${l}` : l,
        );
        doc.push(...rendered);
      }
    }
  }

  // Single trailing newline (MD047); collapse any accidental blank-line runs.
  return doc
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/\s*$/, "") +
    "\n";
}

// -- HTML site ---------------------------------------------------------------

/** Minimal HTML entity-escape for text nodes / attribute values. */
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Render the tiny subset of inline Markdown the catalog uses (`**bold**` and
 * `` `code` ``) into safe HTML. Escapes first, so no raw markup leaks through. */
function inline(s: string): string {
  return esc(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}

/** A generated schematic "screenshot" for a topic: a stylized phone frame with
 * the app bar, the topic on the content area, and the bottom tab bar with this
 * topic's tab highlighted. Purely derived from the catalog, so it can't drift.
 * (Real device screenshots need a browser and are out of CI's reach; this keeps
 * every topic illustrated without a capture step that would go stale.) */
function figureSvg(topic: GuideTopic): string {
  const tabs: { id: GuideTab | "more"; label: string }[] = [
    { id: "maps", label: "Maps" },
    { id: "effects", label: "Effects" },
    { id: "device", label: "Device" },
  ];
  // start/settings topics live behind the ⋯ menu / onboarding, so highlight none
  // of the three primary tabs for them.
  const activeTab: GuideTab | null =
    topic.tab === "maps" || topic.tab === "effects" || topic.tab === "device" ? topic.tab : null;
  const tabW = 300 / tabs.length;
  const tabEls = tabs
    .map((t, i) => {
      const on = t.id === activeTab;
      const cx = 20 + tabW * i + tabW / 2;
      const fill = on ? "var(--fig-accent)" : "var(--fig-dim)";
      return (
        `<circle cx="${cx.toFixed(1)}" cy="545" r="5" fill="${fill}" />` +
        `<text x="${cx.toFixed(1)}" y="565" text-anchor="middle" font-size="11" ` +
        `fill="${fill}">${esc(t.label)}</text>`
      );
    })
    .join("");
  return (
    `<svg viewBox="0 0 340 600" role="img" aria-label="${esc(topic.title)} screen" ` +
    `class="figure-svg" xmlns="http://www.w3.org/2000/svg">` +
    `<rect x="8" y="8" width="324" height="584" rx="28" fill="var(--fig-bg)" ` +
    `stroke="var(--fig-border)" stroke-width="2" />` +
    // app bar
    `<text x="28" y="52" font-size="17" font-weight="700" fill="var(--fig-text)">Splanc</text>` +
    `<rect x="232" y="36" width="80" height="22" rx="11" fill="var(--fig-panel)" />` +
    `<text x="272" y="51" text-anchor="middle" font-size="11" fill="var(--fig-dim)">Device</text>` +
    `<line x1="20" y1="72" x2="320" y2="72" stroke="var(--fig-border)" />` +
    // content: topic title + summary (wrapped)
    `<text x="28" y="112" font-size="16" font-weight="700" fill="var(--fig-accent)">` +
    `${esc(topic.title)}</text>` +
    figureSummary(topic.summary) +
    // tab bar
    `<line x1="20" y1="520" x2="320" y2="520" stroke="var(--fig-border)" />` +
    tabEls +
    `</svg>`
  );
}

/** Lay the summary out as up to three wrapped tspans under the topic title. */
function figureSummary(summary: string): string {
  const lines = wrap(summary, 42).slice(0, 3);
  return lines
    .map(
      (l, i) =>
        `<text x="28" y="${140 + i * 20}" font-size="12" fill="var(--fig-dim)">${esc(l)}</text>`,
    )
    .join("");
}

function renderHtmlTopic(topic: GuideTopic): string {
  const parts: string[] = [];
  parts.push(`<article class="topic" id="${esc(topic.id)}">`);
  // A real captured app screenshot when the topic has one; otherwise the
  // schematic figure generated from the catalog (screens that can't render
  // standalone headless — live device / camera / a specific record).
  const figure = topic.screenshot
    ? `<img class="shot" src="${IMG_DIR}/${esc(topic.id)}.png" alt="${esc(topic.title)} screen" loading="lazy" />`
    : figureSvg(topic);
  parts.push(`<div class="topic-figure">${figure}</div>`);
  parts.push(`<div class="topic-body">`);
  parts.push(`<h3>${esc(topic.title)}</h3>`);
  parts.push(`<p class="summary">${esc(topic.summary)}</p>`);
  for (const sec of topic.sections) {
    if (sec.heading) parts.push(`<h4>${esc(sec.heading)}</h4>`);
    for (const p of sec.body ?? []) parts.push(`<p>${inline(p)}</p>`);
    if ((sec.bullets ?? []).length > 0) {
      parts.push("<ul>");
      for (const b of sec.bullets ?? []) parts.push(`<li>${inline(b)}</li>`);
      parts.push("</ul>");
    }
  }
  parts.push(`</div>`);
  parts.push(`</article>`);
  return parts.join("\n");
}

function renderHtml(): string {
  const groups = groupByTab();
  const nav = groups
    .map(
      (g) =>
        `<div class="nav-group"><div class="nav-head">${esc(GUIDE_TAB_LABELS[g.tab])}</div>` +
        g.topics.map((t) => `<a href="#${esc(t.id)}">${esc(t.title)}</a>`).join("") +
        `</div>`,
    )
    .join("\n");
  const body = groups
    .map(
      (g) =>
        `<section class="tab-section">\n<h2 id="tab-${esc(g.tab)}">` +
        `${esc(GUIDE_TAB_LABELS[g.tab])}</h2>\n` +
        g.topics.map(renderHtmlTopic).join("\n") +
        `\n</section>`,
    )
    .join("\n");

  return `<!doctype html>
<!-- Generated by web/tests/tools/genUserGuide.ts. DO NOT EDIT BY HAND. -->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Splanc user guide</title>
    <meta name="description" content="How to map, control, and animate LED fixtures with Splanc." />
    <style>
${HTML_CSS}
    </style>
  </head>
  <body>
    <header class="site-head">
      <h1>Splanc user guide</h1>
      <p>
        Map, control, and animate addressable LED fixtures from your phone. Take this tour
        interactively in the app from <strong>Settings &#9656; Help &amp; tutorial</strong>.
      </p>
    </header>
    <div class="layout">
      <nav class="toc">
${nav}
      </nav>
      <main>
${body}
      </main>
    </div>
    <footer class="site-foot">
      Generated from the in-app guide catalog. Figures are schematic. See the source at
      <code>web/src/ui/guide/catalog.ts</code>.
    </footer>
  </body>
</html>
`;
}

const HTML_CSS = `      :root {
        --fig-bg: #17171c;
        --fig-panel: #1f1f26;
        --fig-border: #2a2a33;
        --fig-text: #e8e8ea;
        --fig-dim: #9a9aa2;
        --fig-accent: #5b7cfa;
        color-scheme: dark;
      }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        background: #0e0e12;
        color: #e8e8ea;
        font: 16px/1.6 system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
      }
      .site-head {
        padding: 40px 24px 24px;
        max-width: 1080px;
        margin: 0 auto;
        border-bottom: 1px solid #2a2a33;
      }
      .site-head h1 { margin: 0 0 8px; font-size: 2rem; }
      .site-head p { margin: 0; color: #9a9aa2; max-width: 60ch; }
      .layout {
        display: grid;
        grid-template-columns: 220px 1fr;
        gap: 32px;
        max-width: 1080px;
        margin: 0 auto;
        padding: 24px;
      }
      .toc {
        position: sticky;
        top: 16px;
        align-self: start;
        font-size: 0.9rem;
        max-height: calc(100vh - 32px);
        overflow: auto;
      }
      .nav-group { margin-bottom: 16px; }
      .nav-head {
        text-transform: uppercase;
        letter-spacing: 0.05em;
        font-size: 0.7rem;
        color: #9a9aa2;
        margin-bottom: 6px;
      }
      .toc a { display: block; color: #c8c8d0; text-decoration: none; padding: 3px 0; }
      .toc a:hover { color: #5b7cfa; }
      main { min-width: 0; }
      h2 { font-size: 1.4rem; margin: 32px 0 8px; padding-top: 8px; }
      .topic {
        display: grid;
        grid-template-columns: 200px 1fr;
        gap: 24px;
        padding: 24px 0;
        border-top: 1px solid #2a2a33;
      }
      .topic-figure { position: sticky; top: 16px; align-self: start; }
      .figure-svg { width: 100%; height: auto; }
      .topic-body h3 { margin: 0 0 4px; font-size: 1.2rem; }
      .topic-body h4 { margin: 20px 0 6px; font-size: 0.95rem; color: #c8c8d0; }
      .summary { color: #9a9aa2; font-style: italic; margin: 0 0 12px; }
      .shot {
        width: 100%;
        height: auto;
        border-radius: 18px;
        border: 1px solid #2a2a33;
        box-shadow: 0 8px 30px rgba(0, 0, 0, 0.45);
        display: block;
      }
      .topic-body p { margin: 0 0 12px; }
      .topic-body ul { margin: 0 0 12px; padding-left: 20px; }
      .topic-body li { margin: 4px 0; }
      code {
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 0.85em;
        background: #1f1f26;
        padding: 1px 5px;
        border-radius: 5px;
      }
      strong { color: #f0f0f2; }
      .site-foot {
        max-width: 1080px;
        margin: 0 auto;
        padding: 24px;
        color: #9a9aa2;
        font-size: 0.85rem;
        border-top: 1px solid #2a2a33;
      }
      @media (max-width: 760px) {
        .layout { grid-template-columns: 1fr; }
        .toc { position: static; max-height: none; }
        /* Single column: figure becomes a normal block ABOVE the text (not
           sticky), so it can't float over the prose. */
        .topic { grid-template-columns: 1fr; gap: 12px; }
        .topic-figure {
          position: static;
          max-width: 230px;
          margin: 0 0 4px;
        }
      }`;

/** The screenshot manifest the Playwright capturer consumes: the ordered list
 * of {id, route} for every topic with a `screenshot`. Deterministic (stable
 * order, 2-space JSON) so it's a freshness-gated output like the md/html. */
function renderShotsManifest(): string {
  const shots = GUIDE_TOPICS.filter((t) => t.screenshot).map((t) => {
    const shot: { id: string; route: string; click?: string; waitMs?: number } = {
      id: t.id,
      route: t.screenshot as string,
    };
    if (t.screenshotClick) shot.click = t.screenshotClick;
    if (t.screenshotWaitMs) shot.waitMs = t.screenshotWaitMs;
    return shot;
  });
  return JSON.stringify(shots, null, 2) + "\n";
}

// -- CLI ---------------------------------------------------------------------

interface Args {
  check: boolean;
  mdOut: string;
  htmlOut: string;
  shotsOut: string;
}

function resolveArgs(argv: string[]): Args {
  let check = false;
  let mdOut = "";
  let htmlOut = "";
  let shotsOut = "";
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--check") check = true;
    else if (a === "--md-out") mdOut = argv[++i]!;
    else if (a === "--html-out") htmlOut = argv[++i]!;
    else if (a === "--shots-out") shotsOut = argv[++i]!;
  }
  const ws = process.env["BUILD_WORKSPACE_DIRECTORY"];
  if (!mdOut) {
    if (!ws) throw new Error("no --md-out and no BUILD_WORKSPACE_DIRECTORY; pass --md-out <path>");
    mdOut = path.join(ws, MD_REL_PATH);
  }
  if (!htmlOut) {
    if (!ws) throw new Error("no --html-out and no BUILD_WORKSPACE_DIRECTORY; pass --html-out <path>");
    htmlOut = path.join(ws, HTML_REL_PATH);
  }
  if (!shotsOut) {
    if (!ws) throw new Error("no --shots-out and no BUILD_WORKSPACE_DIRECTORY; pass --shots-out <path>");
    shotsOut = path.join(ws, SHOTS_REL_PATH);
  }
  return { check, mdOut, htmlOut, shotsOut };
}

function main(): number {
  const { check, mdOut, htmlOut, shotsOut } = resolveArgs(process.argv.slice(2));
  const outputs: { rel: string; out: string; content: string }[] = [
    { rel: MD_REL_PATH, out: mdOut, content: renderMarkdown() },
    { rel: HTML_REL_PATH, out: htmlOut, content: renderHtml() },
    { rel: SHOTS_REL_PATH, out: shotsOut, content: renderShotsManifest() },
  ];

  if (check) {
    let stale = false;
    for (const o of outputs) {
      const actual = fs.existsSync(o.out) ? fs.readFileSync(o.out, "utf8") : "";
      if (actual !== o.content) {
        stale = true;
        process.stderr.write(`STALE: ${o.rel} is out of date with the guide catalog.\n`);
      }
    }
    if (stale) {
      process.stderr.write(`Run \`${REGEN_CMD}\` to regenerate the user guide.\n`);
      return 1;
    }
    process.stderr.write("user guide is up to date.\n");
    return 0;
  }

  for (const o of outputs) {
    fs.mkdirSync(path.dirname(o.out), { recursive: true });
    fs.writeFileSync(o.out, o.content);
    process.stderr.write(`wrote ${o.rel}\n`);
  }
  return 0;
}

process.exit(main());
